In [2]:
import pandas as pd

In [39]:
df = pd.read_excel('test.xlsx', engine='openpyxl', skiprows=1)

In [49]:
df

  FG_CODE  QTY
0  FG0369   10
1  FG0370   20
2  FG0371   30
3  FG0372   40
4  FG0373   50

In [46]:
json_payload_list = []
for i in range(len(df)):
    json_payload_list.append({'FG_Code' : df.iloc[i]['FG_CODE'], 'FG_Qty' : int(df.iloc[i]['QTY'])})

In [47]:
json_payload_list

[{'FG_Code': 'FG0369', 'FG_Qty': 10},
 {'FG_Code': 'FG0370', 'FG_Qty': 20},
 {'FG_Code': 'FG0371', 'FG_Qty': 30},
 {'FG_Code': 'FG0372', 'FG_Qty': 40},
 {'FG_Code': 'FG0373', 'FG_Qty': 50}]

In [52]:
import json
json.dumps(json_payload_list)

'[{"FG_Code": "FG0369", "FG_Qty": 10}, {"FG_Code": "FG0370", "FG_Qty": 20}, {"FG_Code": "FG0371", "FG_Qty": 30}, {"FG_Code": "FG0372", "FG_Qty": 40}, {"FG_Code": "FG0373", "FG_Qty": 50}]'

In [23]:
combined = dict(zip(df['PX_CODE'],df['RM_CODE']))

In [38]:
combined

{'PX001': 'RM112', 'PX023': 'RM022'}

In [ ]:
[
    {'RM_CODE' : 'RM001',
     'percentage_qty' : 0.30},
     {'RM_CODE' : 'RM002',
     'percentage_qty' : 0.40},
     {'RM_CODE' : 'RM003',
     'percentage_qty' : 0.30},
]

In [22]:
conversion_codes = [
  {
    "PX_Code": "PX014",
    "MD_Code": "MD191095",
    "Formula_Qty": 8,
    "Formula_Percent": 69.5652,
    "Level": 1
  },
  {
    "PX_Code": "PX014",
    "MD_Code": "MD191130",
    "Formula_Qty": 1.5,
    "Formula_Percent": 13.0435,
    "Level": 1
  },
  {
    "PX_Code": "PX014",
    "MD_Code": "MD191139",
    "Formula_Qty": 2,
    "Formula_Percent": 17.3913,
    "Level": 1
  },
  {
    "PX_Code": "PX016",
    "MD_Code": "MD191074",
    "Formula_Qty": 3.6,
    "Formula_Percent": 31.0345,
    "Level": 1
  },
  {
    "PX_Code": "PX016",
    "MD_Code": "MD191079",
    "Formula_Qty": 8,
    "Formula_Percent": 68.9655,
    "Level": 1
  },
  {
    "PX_Code": "PX018A",
    "MD_Code": "MD191039",
    "Formula_Qty": 0.05,
    "Formula_Percent": 1.2346,
    "Level": 1
  },
  {
    "PX_Code": "PX018A",
    "MD_Code": "MD191095",
    "Formula_Qty": 0.3,
    "Formula_Percent": 7.4074,
    "Level": 1
  },{
    "PX_Code": "PX018A",
    "MD_Code": "MD191103",
    "Formula_Qty": 0.5,
    "Formula_Percent": 12.3457,
    "Level": 1
  },
  {
    "PX_Code": "PX018A",
    "MD_Code": "MD191113",
    "Formula_Qty": 1.5,
    "Formula_Percent": 37.037,
    "Level": 1
  },
  {
    "PX_Code": "PX018A",
    "MD_Code": "MD191130",
    "Formula_Qty": 0.5,
    "Formula_Percent": 12.3457,
    "Level": 1
  },
  {
    "PX_Code": "PX018A",
    "MD_Code": "MD191160",
    "Formula_Qty": 1.2,
    "Formula_Percent": 29.6296,
    "Level": 1
  }]

In [29]:
from collections import defaultdict

conversion_dict = defaultdict(list)
for item in conversion_codes:
    px_val = item.get('PX_Code')
    md_val = item.get('MD_Code')
    percentage = item.get('Formula_Percent')
    
    # Appends to a list instead of overwriting
    conversion_dict[px_val].append({
        'MD_code' : md_val,
        'percentage' : percentage
    })

In [30]:
conversion_dict

defaultdict(list,
            {'PX014': [{'MD_code': 'MD191095', 'percentage': 69.5652},
              {'MD_code': 'MD191130', 'percentage': 13.0435},
              {'MD_code': 'MD191139', 'percentage': 17.3913}],
             'PX016': [{'MD_code': 'MD191074', 'percentage': 31.0345},
              {'MD_code': 'MD191079', 'percentage': 68.9655}],
             'PX018A': [{'MD_code': 'MD191039', 'percentage': 1.2346},
              {'MD_code': 'MD191095', 'percentage': 7.4074},
              {'MD_code': 'MD191103', 'percentage': 12.3457},
              {'MD_code': 'MD191113', 'percentage': 37.037},
              {'MD_code': 'MD191130', 'percentage': 12.3457},
              {'MD_code': 'MD191160', 'percentage': 29.6296}]})

In [36]:
px_items = [{'Item_Code': 'PX014', 'Total_Qty': 0.0595}, {'Item_Code': 'PX016', 'Total_Qty': 0.215}, {'Item_Code': 'PX221A', 'Total_Qty': 0.119}, {'Item_Code': 'PX221B', 'Total_Qty': 0.43}]

In [37]:
px_items

[{'Item_Code': 'PX014', 'Total_Qty': 0.0595},
 {'Item_Code': 'PX016', 'Total_Qty': 0.215},
 {'Item_Code': 'PX221A', 'Total_Qty': 0.119},
 {'Item_Code': 'PX221B', 'Total_Qty': 0.43}]

In [52]:
conversion_dict[px_items[0].get('Item_Code')]

[{'MD_code': 'MD191095', 'percentage': 69.5652},
 {'MD_code': 'MD191130', 'percentage': 13.0435},
 {'MD_code': 'MD191139', 'percentage': 17.3913}]

In [74]:
final_list = []
for px_code in px_items:
    # print(px_code)
    # final_list.extend(conversion_dict[px_code.get('Item_Code')])
    for item in conversion_dict[px_code.get('Item_Code')]:
        final_list.append({'MD_code' : item.get('MD_code'),
         'Qty' : (item.get('percentage')/100)*px_code.get('Total_Qty')})
print(final_list)

[{'MD_code': 'MD191095', 'Qty': 0.041391294}, {'MD_code': 'MD191130', 'Qty': 0.007760882499999999}, {'MD_code': 'MD191139', 'Qty': 0.0103478235}, {'MD_code': 'MD191074', 'Qty': 0.06672417500000001}, {'MD_code': 'MD191079', 'Qty': 0.148275825}]

In [73]:
sum = 0.041391294 + 0.007760882499999999 + 0.0103478235
# for item in final_list:
#     if item.get('MD_code') == 'MD191095':
#         sum += item.get('Qty')

print(sum)

0.0595

In [82]:
converted_px_to_md = [{'MD_code': 'MD191099', 'Qty': 0.0599998}, {'MD_code': 'MD191100', 'Qty': 0.04499985}, {'MD_code': 'MD191103', 'Qty': 0.099999865}, {'MD_code': 'MD191130', 'Qty': 0.09000029499999998}, {'MD_code': 'MD191194', 'Qty': 0.30000019}, {'MD_code': 'MD191005', 'Qty': 0.4999997}, {'MD_code': 'MD191057', 'Qty': 0.19999945000000002}, {'MD_code': 'MD191067', 'Qty': 0.19999945000000002}, {'MD_code': 'MD191087', 'Qty': 0.6000004999999999}, {'MD_code': 'MD191104', 'Qty': 0.40000105}, {'MD_code': 'MD191159', 'Qty': 0.24999985}, {'MD_code': 'MD191099', 'Qty': 0.0599998}, {'MD_code': 'MD191100', 'Qty': 0.04499985}, {'MD_code': 'MD191103', 'Qty': 0.099999865}, {'MD_code': 'MD191130', 'Qty': 0.09000029499999998}, {'MD_code': 'MD191194', 'Qty': 0.30000019}, {'MD_code': 'MD191005', 'Qty': 0.4999997}, {'MD_code': 'MD191057', 'Qty': 0.19999945000000002}, {'MD_code': 'MD191067', 'Qty': 0.19999945000000002}, {'MD_code': 'MD191087', 'Qty': 0.6000004999999999}, {'MD_code': 'MD191104', 'Qty': 0.40000105}, {'MD_code': 'MD191159', 'Qty': 0.24999985}]

In [83]:
converted_px_to_md

[{'MD_code': 'MD191099', 'Qty': 0.0599998},
 {'MD_code': 'MD191100', 'Qty': 0.04499985},
 {'MD_code': 'MD191103', 'Qty': 0.099999865},
 {'MD_code': 'MD191130', 'Qty': 0.09000029499999998},
 {'MD_code': 'MD191194', 'Qty': 0.30000019},
 {'MD_code': 'MD191005', 'Qty': 0.4999997},
 {'MD_code': 'MD191057', 'Qty': 0.19999945000000002},
 {'MD_code': 'MD191067', 'Qty': 0.19999945000000002},
 {'MD_code': 'MD191087', 'Qty': 0.6000004999999999},
 {'MD_code': 'MD191104', 'Qty': 0.40000105},
 {'MD_code': 'MD191159', 'Qty': 0.24999985},
 {'MD_code': 'MD191099', 'Qty': 0.0599998},
 {'MD_code': 'MD191100', 'Qty': 0.04499985},
 {'MD_code': 'MD191103', 'Qty': 0.099999865},
 {'MD_code': 'MD191130', 'Qty': 0.09000029499999998},
 {'MD_code': 'MD191194', 'Qty': 0.30000019},
 {'MD_code': 'MD191005', 'Qty': 0.4999997},
 {'MD_code': 'MD191057', 'Qty': 0.19999945000000002},
 {'MD_code': 'MD191067', 'Qty': 0.19999945000000002},
 {'MD_code': 'MD191087', 'Qty': 0.6000004999999999},
 {'MD_code': 'MD191104', 'Qty': 0.40000105},
 {'MD_code': 'MD191159', 'Qty': 0.24999985}]

In [84]:
px_items_new = [{'Item_Code': 'PX227A', 'Total_Qty': 539.1875}, {'Item_Code': 'PX227B', 'Total_Qty': 1164.645}, {'Item_Code': 'PX237A', 'Total_Qty': 6.461}, {'Item_Code': 'PX237B', 'Total_Qty': 29.2946}, {'Item_Code': 'PX273A', 'Total_Qty': 18.4853}, {'Item_Code': 'PX273B', 'Total_Qty': 222.0801}, {'Item_Code': 'PX179', 'Total_Qty': 11.9454}, {'Item_Code': 'PX229A', 'Total_Qty': 136.1485}, {'Item_Code': 'PX229B', 'Total_Qty': 289.1676}, {'Item_Code': 'PX461', 'Total_Qty': 188.6411}, {'Item_Code': 'PX149A', 'Total_Qty': 723.7342}, {'Item_Code': 'PX149B', 'Total_Qty': 838.3907}, {'Item_Code': 'PX150A', 'Total_Qty': 544.486}, {'Item_Code': 'PX150B', 'Total_Qty': 531.097}, {'Item_Code': 'PX186A', 'Total_Qty': 4.472}, {'Item_Code': 'PX186B', 'Total_Qty': 4.128}, {'Item_Code': 'PX188A', 'Total_Qty': 7.361}, {'Item_Code': 'PX188B', 'Total_Qty': 35.506}, {'Item_Code': 'PX190', 'Total_Qty': 1108.03}, {'Item_Code': 'PX191', 'Total_Qty': 20.52}, {'Item_Code': 'PX488', 'Total_Qty': 5345.16}, {'Item_Code': 'PX196', 'Total_Qty': 93.0}, {'Item_Code': 'PX197', 'Total_Qty': 10.92}, {'Item_Code': 'PX198', 'Total_Qty': 32.554}, {'Item_Code': 'PX072', 'Total_Qty': 1330.4}, {'Item_Code': 'PX205', 'Total_Qty': 40.672}, {'Item_Code': 'PX358', 'Total_Qty': 265.8}, {'Item_Code': 'PX208', 'Total_Qty': 98.64}, {'Item_Code': 'PX210', 'Total_Qty': 0.0}, {'Item_Code': 'PX212', 'Total_Qty': 14.7}, {'Item_Code': 'PX213', 'Total_Qty': 10.064}, {'Item_Code': 'PX335', 'Total_Qty': 13.5}, {'Item_Code': 'PX217', 'Total_Qty': 2.0}, {'Item_Code': 'PX223A', 'Total_Qty': 1846.0529999999999}, {'Item_Code': 'PX223B', 'Total_Qty': 6670.6115}, {'Item_Code': 'PX513A', 'Total_Qty': 2196.046}, {'Item_Code': 'PX513C', 'Total_Qty': 5287.4922}, {'Item_Code': 'PX240A', 'Total_Qty': 155.103}, {'Item_Code': 'PX240B', 'Total_Qty': 94.575}, {'Item_Code': 'PX241', 'Total_Qty': 12.6}, {'Item_Code': 'PX283A', 'Total_Qty': 0.0}, {'Item_Code': 'PX283B', 'Total_Qty': 0.0}, {'Item_Code': 'PX158A', 'Total_Qty': 312.8992}, {'Item_Code': 'PX158B', 'Total_Qty': 664.8}, {'Item_Code': 'PX156A', 'Total_Qty': 495.842}, {'Item_Code': 'PX156B', 'Total_Qty': 997.4608}, {'Item_Code': 'PX068A', 'Total_Qty': 1174.474}, {'Item_Code': 'PX068B', 'Total_Qty': 796.2059999999999}, {'Item_Code': 'PX066', 'Total_Qty': 1795.5}, {'Item_Code': 'PX244A', 'Total_Qty': 6.4832}, {'Item_Code': 'PX244B', 'Total_Qty': 8.992}, {'Item_Code': 'PX245A', 'Total_Qty': 4.18}, {'Item_Code': 'PX245B', 'Total_Qty': 4.592}, {'Item_Code': 'PX225A', 'Total_Qty': 304.4496}, {'Item_Code': 'PX225B', 'Total_Qty': 1100.112}, {'Item_Code': 'PX069A', 'Total_Qty': 641.9936}, {'Item_Code': 'PX069B', 'Total_Qty': 781.1044}, {'Item_Code': 'PX067', 'Total_Qty': 180.96}, {'Item_Code': 'PX246', 'Total_Qty': 800.4}, {'Item_Code': 'PX261', 'Total_Qty': 971.288}, {'Item_Code': 'PX453A', 'Total_Qty': 155.4479}, {'Item_Code': 'PX453B', 'Total_Qty': 236.8105}, {'Item_Code': 'PX018A', 'Total_Qty': 952.3575000000001}, {'Item_Code': 'PX018B', 'Total_Qty': 1810.6550000000002}, {'Item_Code': 'PX151A', 'Total_Qty': 34.0848}, {'Item_Code': 'PX151B', 'Total_Qty': 63.828}, {'Item_Code': 'PX152A', 'Total_Qty': 138.544}, {'Item_Code': 'PX152B', 'Total_Qty': 106.382}, {'Item_Code': 'PX133A', 'Total_Qty': 18.5087}, {'Item_Code': 'PX133B', 'Total_Qty': 140.3689}, {'Item_Code': 'PX052A', 'Total_Qty': 313.9174}, {'Item_Code': 'PX052B', 'Total_Qty': 371.7266}, {'Item_Code': 'PX460A', 'Total_Qty': 216.315}, {'Item_Code': 'PX460B', 'Total_Qty': 264.385}, {'Item_Code': 'PX248', 'Total_Qty': 131.6352}, {'Item_Code': 'PX088', 'Total_Qty': 112.3151}, {'Item_Code': 'PX118', 'Total_Qty': 229.09919999999997}, {'Item_Code': 'PX340', 'Total_Qty': 143.3764}, {'Item_Code': 'PX173', 'Total_Qty': 27.230400000000003}, {'Item_Code': 'PX360', 'Total_Qty': 133.92}, {'Item_Code': 'PX337', 'Total_Qty': 48.408}, {'Item_Code': 'PX338', 'Total_Qty': 4.824}, {'Item_Code': 'PX387', 'Total_Qty': 123.2474}, {'Item_Code': 'PX469A', 'Total_Qty': 883.2031}, {'Item_Code': 'PX469B', 'Total_Qty': 469.5189}, {'Item_Code': 'PX352A', 'Total_Qty': 1624.7264}, {'Item_Code': 'PX352B', 'Total_Qty': 2289.3872}, {'Item_Code': 'PX414', 'Total_Qty': 3139.0}, {'Item_Code': 'PX233A', 'Total_Qty': 226.9313}, {'Item_Code': 'PX233B', 'Total_Qty': 490.1715}, {'Item_Code': 'PX271A', 'Total_Qty': 169.6438}, {'Item_Code': 'PX271B', 'Total_Qty': 366.4305}, {'Item_Code': 'PX472A', 'Total_Qty': 3717.1888}, {'Item_Code': 'PX472C', 'Total_Qty': 1831.0305}, {'Item_Code': 'PX253', 'Total_Qty': 0.0}, {'Item_Code': 'PX336', 'Total_Qty': 65.281}, {'Item_Code': 'PX267', 'Total_Qty': 108.58}, {'Item_Code': 'PX434A', 'Total_Qty': 87.842}, {'Item_Code': 'PX434B', 'Total_Qty': 58.649}, {'Item_Code': 'PX255A', 'Total_Qty': 5.145}, {'Item_Code': 'PX255B', 'Total_Qty': 5.586}, {'Item_Code': 'PX256A', 'Total_Qty': 1.554}, {'Item_Code': 'PX256B', 'Total_Qty': 5.796}, {'Item_Code': 'PX257', 'Total_Qty': 10.6624}, {'Item_Code': 'PX424A', 'Total_Qty': 489.64099999999996}, {'Item_Code': 'PX424B', 'Total_Qty': 981.5594000000001}, {'Item_Code': 'PX367A', 'Total_Qty': 16.6}, {'Item_Code': 'PX367B', 'Total_Qty': 21.0}, {'Item_Code': 'PX276', 'Total_Qty': 13.0}, {'Item_Code': 'PX289', 'Total_Qty': 13.761}, {'Item_Code': 'PX306A', 'Total_Qty': 0.0}, {'Item_Code': 'PX306B', 'Total_Qty': 0.0}, {'Item_Code': 'PX278A', 'Total_Qty': 2.485}, {'Item_Code': 'PX401A', 'Total_Qty': 269.3121}, {'Item_Code': 'PX401B', 'Total_Qty': 314.73}, {'Item_Code': 'PX063A', 'Total_Qty': 27.7544}, {'Item_Code': 'PX063B', 'Total_Qty': 21.1021}, {'Item_Code': 'PX376A', 'Total_Qty': 781.2282}, {'Item_Code': 'PX376B', 'Total_Qty': 3149.4539999999997}, {'Item_Code': 'PX412', 'Total_Qty': 487.5321}, {'Item_Code': 'PX356A', 'Total_Qty': 0.0}, {'Item_Code': 'PX356B', 'Total_Qty': 0.0}, {'Item_Code': 'PX160', 'Total_Qty': 0.0}, {'Item_Code': 'PX375', 'Total_Qty': 1045.1988}, {'Item_Code': 'PX381A', 'Total_Qty': 63.6405}, {'Item_Code': 'PX381B', 'Total_Qty': 62.9793}, {'Item_Code': 'PX382A', 'Total_Qty': 16.6166}, {'Item_Code': 'PX382B', 'Total_Qty': 10.4286}, {'Item_Code': 'PX359A', 'Total_Qty': 2045.1113}, {'Item_Code': 'PX359B', 'Total_Qty': 1641.4125}, {'Item_Code': 'PX129A', 'Total_Qty': 246.587}, {'Item_Code': 'PX129B', 'Total_Qty': 2416.5526}, {'Item_Code': 'PX393A', 'Total_Qty': 55.2244}, {'Item_Code': 'PX393B', 'Total_Qty': 259.2678}, {'Item_Code': 'PX393C', 'Total_Qty': 222.332}, {'Item_Code': 'PX290A', 'Total_Qty': 1.7182}, {'Item_Code': 'PX290B', 'Total_Qty': 19.4689}, {'Item_Code': 'PX292A', 'Total_Qty': 0.585}, {'Item_Code': 'PX292B', 'Total_Qty': 5.823}, {'Item_Code': 'PX470A', 'Total_Qty': 433.789}, {'Item_Code': 'PX470B', 'Total_Qty': 922.3724}, {'Item_Code': 'PX484', 'Total_Qty': 69.4017}, {'Item_Code': 'PX192', 'Total_Qty': 0.6771}, {'Item_Code': 'PX364', 'Total_Qty': 974.8524}, {'Item_Code': 'PX388', 'Total_Qty': 2.592}, {'Item_Code': 'PX366A', 'Total_Qty': 445.627}, {'Item_Code': 'PX366B', 'Total_Qty': 537.726}, {'Item_Code': 'PX408', 'Total_Qty': 12285.732}, {'Item_Code': 'PX266A', 'Total_Qty': 55.601}, {'Item_Code': 'PX266B', 'Total_Qty': 93.7885}, {'Item_Code': 'PX249A', 'Total_Qty': 5.754}, {'Item_Code': 'PX249B', 'Total_Qty': 4.932}, {'Item_Code': 'PX111', 'Total_Qty': 1.3176}, {'Item_Code': 'PX301A', 'Total_Qty': 0.6739}, {'Item_Code': 'PX301B', 'Total_Qty': 15.2885}, {'Item_Code': 'PX331A', 'Total_Qty': 11.745}, {'Item_Code': 'PX331B', 'Total_Qty': 2.6244}, {'Item_Code': 'PX065', 'Total_Qty': 393.0}, {'Item_Code': 'PX479A', 'Total_Qty': 4757.238}, {'Item_Code': 'PX433A', 'Total_Qty': 9.576}, {'Item_Code': 'PX433B', 'Total_Qty': 8.4}, {'Item_Code': 'PX425A', 'Total_Qty': 2727.072}, {'Item_Code': 'PX425B', 'Total_Qty': 1082.808}, {'Item_Code': 'PX428A', 'Total_Qty': 1946.808}, {'Item_Code': 'PX429A', 'Total_Qty': 3.8304}, {'Item_Code': 'PX429B', 'Total_Qty': 39.4624}, {'Item_Code': 'PX467A', 'Total_Qty': 2.6645}, {'Item_Code': 'PX467B', 'Total_Qty': 40.7919}, {'Item_Code': 'PX416', 'Total_Qty': 76.0859}, {'Item_Code': 'PX415', 'Total_Qty': 24.0429}, {'Item_Code': 'PX489A', 'Total_Qty': 0.0}, {'Item_Code': 'PX489B', 'Total_Qty': 0.0}, {'Item_Code': 'PX490A', 'Total_Qty': 0.0}, {'Item_Code': 'PX490B', 'Total_Qty': 0.0}, {'Item_Code': 'PX501', 'Total_Qty': 130.7455}, {'Item_Code': 'PX515', 'Total_Qty': 408.3393}, {'Item_Code': 'PX510A', 'Total_Qty': 11.1014}, {'Item_Code': 'PX510B', 'Total_Qty': 17.5701}, {'Item_Code': 'PX493A', 'Total_Qty': 33.6088}, {'Item_Code': 'PX493B', 'Total_Qty': 48.1411}, {'Item_Code': 'PX282A', 'Total_Qty': 513.5073}, {'Item_Code': 'PX282B', 'Total_Qty': 303.4361}, {'Item_Code': 'PX503A', 'Total_Qty': 1378.2223}, {'Item_Code': 'PX503B', 'Total_Qty': 4980.131}, {'Item_Code': 'PX504A', 'Total_Qty': 11.9}, {'Item_Code': 'PX504B', 'Total_Qty': 43.0}, {'Item_Code': 'PX505A', 'Total_Qty': 0.0}, {'Item_Code': 'PX505B', 'Total_Qty': 0.0}, {'Item_Code': 'PX507A', 'Total_Qty': 100.575}, {'Item_Code': 'PX507B', 'Total_Qty': 34.27}, {'Item_Code': 'PX357A', 'Total_Qty': 0.0}, {'Item_Code': 'PX357B', 'Total_Qty': 0.0}, {'Item_Code': 'PX399A', 'Total_Qty': 0.0}, {'Item_Code': 'PX399B', 'Total_Qty': 0.0}, {'Item_Code': 'PX378A', 'Total_Qty': 0.0}, {'Item_Code': 'PX378B', 'Total_Qty': 0.0}, {'Item_Code': 'PX444A', 'Total_Qty': 0.0}, {'Item_Code': 'PX444B', 'Total_Qty': 0.0}, {'Item_Code': 'PX481A', 'Total_Qty': 1269.6995}, {'Item_Code': 'PX481B', 'Total_Qty': 2930.6658}, {'Item_Code': 'PX511A', 'Total_Qty': 177.1}, {'Item_Code': 'PX511B', 'Total_Qty': 108.9}, {'Item_Code': 'PX512A', 'Total_Qty': 125.46}, {'Item_Code': 'PX512B', 'Total_Qty': 86.76}, {'Item_Code': 'PX303A', 'Total_Qty': 24.2008}, {'Item_Code': 'PX303B', 'Total_Qty': 347.2815}, {'Item_Code': 'PX309', 'Total_Qty': 38.6982}, {'Item_Code': 'PX310', 'Total_Qty': 47.9063}, {'Item_Code': 'PX311A', 'Total_Qty': 7.2158}, {'Item_Code': 'PX311B', 'Total_Qty': 99.4787}, {'Item_Code': 'PX313', 'Total_Qty': 29.8376}, {'Item_Code': 'PX314', 'Total_Qty': 37.6808}, {'Item_Code': 'PX315A', 'Total_Qty': 12.7136}, {'Item_Code': 'PX315B', 'Total_Qty': 191.7132}, {'Item_Code': 'PX317', 'Total_Qty': 49.2946}, {'Item_Code': 'PX318', 'Total_Qty': 56.6773}, {'Item_Code': 'PX350A', 'Total_Qty': 10.545}, {'Item_Code': 'PX350B', 'Total_Qty': 15.4185}, {'Item_Code': 'PX395A', 'Total_Qty': 0.0}, {'Item_Code': 'PX395B', 'Total_Qty': 0.0}, {'Item_Code': 'PX417', 'Total_Qty': 95.8104}, {'Item_Code': 'PX422', 'Total_Qty': 16.632}, {'Item_Code': 'PX438A', 'Total_Qty': 14.006}, {'Item_Code': 'PX438B', 'Total_Qty': 21.754}, {'Item_Code': 'PX445A', 'Total_Qty': 0.0}, {'Item_Code': 'PX445B', 'Total_Qty': 0.0}, {'Item_Code': 'PX435A', 'Total_Qty': 0.0}, {'Item_Code': 'PX435B', 'Total_Qty': 0.0}, {'Item_Code': 'PX455A', 'Total_Qty': 0.0}, {'Item_Code': 'PX455B', 'Total_Qty': 0.0}, {'Item_Code': 'PX466A', 'Total_Qty': 628.6}, {'Item_Code': 'PX466B', 'Total_Qty': 2514.4}, {'Item_Code': 'PX482', 'Total_Qty': 120.75}, {'Item_Code': 'PX483', 'Total_Qty': 349.3647}, {'Item_Code': 'PX495A', 'Total_Qty': 84.5496}, {'Item_Code': 'PX495B', 'Total_Qty': 52.9196}, {'Item_Code': 'PX485A', 'Total_Qty': 0.0}, {'Item_Code': 'PX485B', 'Total_Qty': 0.0}, {'Item_Code': 'PX477A', 'Total_Qty': 0.0}, {'Item_Code': 'PX477B', 'Total_Qty': 0.0}, {'Item_Code': 'PX486', 'Total_Qty': 5.46}, {'Item_Code': 'PX475A', 'Total_Qty': 0.0}]

In [85]:
md_items = [{'MD_code': 'MD191007', 'Qty': 258.81}, {'MD_code': 'MD191099', 'Qty': 51.762}, {'MD_code': 'MD191100', 'Qty': 47.4485}, {'MD_code': 'MD191103', 'Qty': 86.27}, {'MD_code': 'MD191130', 'Qty': 94.897}, {'MD_code': 'MD191005', 'Qty': 345.07965492}, {'MD_code': 'MD191067', 'Qty': 129.404870595}, {'MD_code': 'MD191087', 'Qty': 345.07965492}, {'MD_code': 'MD191104', 'Qty': 172.53982746}, {'MD_code': 'MD191159', 'Qty': 172.53982746}, {'MD_code': 'MD191095', 'Qty': 0.35499964500000003}, {'MD_code': 'MD191103', 'Qty': 5.6800007809999995}, {'MD_code': 'MD191115', 'Qty': 0.425999574}, {'MD_code': 'MD191067', 'Qty': 0.7383996876}, {'MD_code': 'MD191073', 'Qty': 5.679988583199999}, {'MD_code': 'MD191080', 'Qty': 2.0590002556}, {'MD_code': 'MD191085', 'Qty': 1.7608105222}, {'MD_code': 'MD191094', 'Qty': 0.24138750399999997}, {'MD_code': 'MD191097', 'Qty': 0.3549919628}, {'MD_code': 'MD191127', 'Qty': 11.360006461}, {'MD_code': 'MD191172', 'Qty': 7.099985729}, {'MD_code': 'MD191095', 'Qty': 9.24265}, {'MD_code': 'MD191103', 'Qty': 6.9319875}, {'MD_code': 'MD191130', 'Qty': 2.3106625}, {'MD_code': 'MD191073', 'Qty': 127.24967649899999}, {'MD_code': 'MD191074', 'Qty': 23.1298644951}, {'MD_code': 'MD191079', 'Qty': 23.1298644951}, {'MD_code': 'MD191106', 'Qty': 46.2599510703}, {'MD_code': 'MD191222', 'Qty': 2.3107434404999996}, {'MD_code': 'MD191038', 'Qty': 4.299997583400001}, {'MD_code': 'MD191102', 'Qty': 0.02150172}, {'MD_code': 'MD191120', 'Qty': 0.08599493459999999}, {'MD_code': 'MD191130', 'Qty': 0.1720018146}, {'MD_code': 'MD191142', 'Qty': 0.008600687999999999}, {'MD_code': 'MD191152', 'Qty': 0.08599493459999999}, {'MD_code': 'MD191153', 'Qty': 0.025802064}, {'MD_code': 'MD191168', 'Qty': 0.08599493459999999}, {'MD_code': 'MD191169', 'Qty': 0.017201375999999997}, {'MD_code': 'MD191170', 'Qty': 0.004300343999999999}, {'MD_code': 'MD191172', 'Qty': 7.137997660799999}, {'MD_code': 'MD191007', 'Qty': 64.127849579}, {'MD_code': 'MD191099', 'Qty': 12.8255971455}, {'MD_code': 'MD191100', 'Qty': 11.839065114500002}, {'MD_code': 'MD191103', 'Qty': 23.677994080500003}, {'MD_code': 'MD191130', 'Qty': 23.677994080500003}, {'MD_code': 'MD191005', 'Qty': 85.86195713279999}, {'MD_code': 'MD191067', 'Qty': 32.5683684528}, {'MD_code': 'MD191087', 'Qty': 85.86195713279999}, {'MD_code': 'MD191104', 'Qty': 42.4376586408}, {'MD_code': 'MD191159', 'Qty': 42.4376586408}, {'MD_code': 'MD191017', 'Qty': 115.2510346094}, {'MD_code': 'MD191115', 'Qty': 36.2030567065}, {'MD_code': 'MD191225', 'Qty': 37.1870086841}, {'MD_code': 'MD191095', 'Qty': 55.930178976}, {'MD_code': 'MD191103', 'Qty': 22.3720715904}, {'MD_code': 'MD191109', 'Qty': 22.3720715904}, {'MD_code': 'MD191130', 'Qty': 27.965089488}, {'MD_code': 'MD191131', 'Qty': 559.3003422916}, {'MD_code': 'MD191170', 'Qty': 35.7951697978}, {'MD_code': 'MD191073', 'Qty': 489.38709618539997}, {'MD_code': 'MD191087', 'Qty': 44.7440732683}, {'MD_code': 'MD191097', 'Qty': 78.30233781720001}, {'MD_code': 'MD191146', 'Qty': 114.0974287537}, {'MD_code': 'MD191266', 'Qty': 111.85976397540001}, {'MD_code': 'MD191038', 'Qty': 245.46517852}, {'MD_code': 'MD191039', 'Qty': 14.727801814}, {'MD_code': 'MD191095', 'Qty': 22.315214223999998}, {'MD_code': 'MD191103', 'Qty': 13.38891074}, {'MD_code': 'MD191113', 'Qty': 44.629883962}, {'MD_code': 'MD191130', 'Qty': 3.124260668}, {'MD_code': 'MD191131', 'Qty': 200.83475007199996}, {'MD_code': 'MD191073', 'Qty': 111.574982148}, {'MD_code': 'MD191085', 'Qty': 44.630205298}, {'MD_code': 'MD191097', 'Qty': 17.851763460999997}, {'MD_code': 'MD191146', 'Qty': 44.630205298}, {'MD_code': 'MD191172', 'Qty': 312.40984379500003}, {'MD_code': 'MD191007', 'Qty': 0.064499656}, {'MD_code': 'MD191057', 'Qty': 3.719501032}, {'MD_code': 'MD191100', 'Qty': 0.430000688}, {'MD_code': 'MD191133', 'Qty': 0.257998624}, {'MD_code': 'MD191085', 'Qty': 1.548}, {'MD_code': 'MD191189', 'Qty': 2.58}, {'MD_code': 'MD191007', 'Qty': 1.2990030309999998}, {'MD_code': 'MD191100', 'Qty': 4.329997835}, {'MD_code': 'MD191133', 'Qty': 1.731999134}, {'MD_code': 'MD191085', 'Qty': 13.856003463999999}, {'MD_code': 'MD191189', 'Qty': 21.649996536}, {'MD_code': 'MD191100', 'Qty': 483.50440292}, {'MD_code': 'MD191117', 'Qty': 71.94992805000001}, {'MD_code': 'MD191120', 'Qty': 495.01572659}, {'MD_code': 'MD191145', 'Qty': 34.53618707}, {'MD_code': 'MD191190', 'Qty': 23.023755370000003}, {'MD_code': 'MD191100', 'Qty': 5.40000216}, {'MD_code': 'MD191182', 'Qty': 8.64000756}, {'MD_code': 'MD191183', 'Qty': 6.47999028}, {'MD_code': 'MD191057', 'Qty': 801.774}, {'MD_code': 'MD191100', 'Qty': 534.516}, {'MD_code': 'MD191103', 'Qty': 222.71678171999997}, {'MD_code': 'MD191133', 'Qty': 222.71678171999997}, {'MD_code': 'MD191189', 'Qty': 2227.15178172}, {'MD_code': 'MD191266', 'Qty': 1336.29}, {'MD_code': 'MD191001', 'Qty': 52.080000000000005}, {'MD_code': 'MD191115', 'Qty': 22.32}, {'MD_code': 'MD191130', 'Qty': 18.6}, {'MD_code': 'MD191057', 'Qty': 6.720004199999999}, {'MD_code': 'MD191183', 'Qty': 4.1999958}, {'MD_code': 'MD191057', 'Qty': 13.120010742000002}, {'MD_code': 'MD191100', 'Qty': 16.974013694000003}, {'MD_code': 'MD191117', 'Qty': 2.460008118}, {'MD_code': 'MD191001', 'Qty': 712.7618000000001}, {'MD_code': 'MD191057', 'Qty': 444.021}, {'MD_code': 'MD191100', 'Qty': 78.49360000000001}, {'MD_code': 'MD191117', 'Qty': 95.12360000000001}, {'MD_code': 'MD191100', 'Qty': 35.25998032}, {'MD_code': 'MD191110', 'Qty': 2.460005248}, {'MD_code': 'MD191268', 'Qty': 2.9520144319999995}, {'MD_code': 'MD191100', 'Qty': 132.9}, {'MD_code': 'MD191130', 'Qty': 132.9}, {'MD_code': 'MD191065', 'Qty': 32.879967119999996}, {'MD_code': 'MD191117', 'Qty': 65.76003288}, {'MD_code': 'MD191065', 'Qty': 0.0}, {'MD_code': 'MD191117', 'Qty': 0.0}, {'MD_code': 'MD191100', 'Qty': 9.8000049}, {'MD_code': 'MD191130', 'Qty': 4.8999951}, {'MD_code': 'MD191117', 'Qty': 1.183999408}, {'MD_code': 'MD191133', 'Qty': 8.880000592}, {'MD_code': 'MD191090', 'Qty': 8.1}, {'MD_code': 'MD191189', 'Qty': 5.4}, {'MD_code': 'MD191057', 'Qty': 1.0}, {'MD_code': 'MD191100', 'Qty': 1.0}, {'MD_code': 'MD191099', 'Qty': 186.15598451999998}, {'MD_code': 'MD191100', 'Qty': 139.61698839}, {'MD_code': 'MD191103', 'Qty': 310.26058955099995}, {'MD_code': 'MD191130', 'Qty': 279.23582283299993}, {'MD_code': 'MD191194', 'Qty': 930.783614706}, {'MD_code': 'MD191005', 'Qty': 1551.304069217}, {'MD_code': 'MD191057', 'Qty': 620.5202935645001}, {'MD_code': 'MD191067', 'Qty': 620.5202935645001}, {'MD_code': 'MD191087', 'Qty': 1861.5675513049998}, {'MD_code': 'MD191104', 'Qty': 1241.0472577405}, {'MD_code': 'MD191159', 'Qty': 775.6520346085}, {'MD_code': 'MD191099', 'Qty': 250.867510856}, {'MD_code': 'MD191100', 'Qty': 231.568658608}, {'MD_code': 'MD191103', 'Qty': 463.137317216}, {'MD_code': 'MD191115', 'Qty': 555.766537496}, {'MD_code': 'MD191130', 'Qty': 231.568658608}, {'MD_code': 'MD191194', 'Qty': 463.137317216}, {'MD_code': 'MD191005', 'Qty': 926.2734585804}, {'MD_code': 'MD191067', 'Qty': 926.2734585804}, {'MD_code': 'MD191087', 'Qty': 1678.8739483595998}, {'MD_code': 'MD191120', 'Qty': 926.2734585804}, {'MD_code': 'MD191159', 'Qty': 829.7873009148001}, {'MD_code': 'MD191015', 'Qty': 7.274951112000001}, {'MD_code': 'MD191100', 'Qty': 87.300033756}, {'MD_code': 'MD191110', 'Qty': 8.729972355000001}, {'MD_code': 'MD191194', 'Qty': 36.375065766000006}, {'MD_code': 'MD191268', 'Qty': 15.422977011}, {'MD_code': 'MD191120', 'Qty': 72.750021825}, {'MD_code': 'MD191159', 'Qty': 21.824978175}, {'MD_code': 'MD191100', 'Qty': 8.757}, {'MD_code': 'MD191183', 'Qty': 3.843}, {'MD_code': 'MD191099', 'Qty': 0.0}, {'MD_code': 'MD191100', 'Qty': 0.0}, {'MD_code': 'MD191115', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191005', 'Qty': 0.0}, {'MD_code': 'MD191067', 'Qty': 0.0}, {'MD_code': 'MD191087', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.0}, {'MD_code': 'MD191104', 'Qty': 0.0}, {'MD_code': 'MD191189', 'Qty': 0.0}, {'MD_code': 'MD191265', 'Qty': 0.0}, {'MD_code': 'MD191038', 'Qty': 177.27992554240004}, {'MD_code': 'MD191100', 'Qty': 15.955356006399999}, {'MD_code': 'MD191103', 'Qty': 17.7279299744}, {'MD_code': 'MD191113', 'Qty': 66.48012852800001}, {'MD_code': 'MD191133', 'Qty': 13.2960257056}, {'MD_code': 'MD191141', 'Qty': 22.1601471424}, {'MD_code': 'MD191189', 'Qty': 531.84}, {'MD_code': 'MD191266', 'Qty': 132.96}, {'MD_code': 'MD191038', 'Qty': 192.5602407}, {'MD_code': 'MD191100', 'Qty': 86.651860394}, {'MD_code': 'MD191113', 'Qty': 168.49008665200003}, {'MD_code': 'MD191133', 'Qty': 48.139812254}, {'MD_code': 'MD191189', 'Qty': 708.6210888400001}, {'MD_code': 'MD191266', 'Qty': 288.83971116}, {'MD_code': 'MD191100', 'Qty': 767.003164914}, {'MD_code': 'MD191115', 'Qty': 95.87583604199999}, {'MD_code': 'MD191117', 'Qty': 167.781832218}, {'MD_code': 'MD191130', 'Qty': 143.81316682599999}, {'MD_code': 'MD191110', 'Qty': 72.38229125399998}, {'MD_code': 'MD191120', 'Qty': 723.8237087459999}, {'MD_code': 'MD191057', 'Qty': 1173.0594015}, {'MD_code': 'MD191100', 'Qty': 239.3994015}, {'MD_code': 'MD191115', 'Qty': 119.70059849999998}, {'MD_code': 'MD191117', 'Qty': 119.70059849999998}, {'MD_code': 'MD191130', 'Qty': 143.64000000000001}, {'MD_code': 'MD191067', 'Qty': 0.1279978176}, {'MD_code': 'MD191095', 'Qty': 0.6400020544}, {'MD_code': 'MD191098', 'Qty': 2.2399974656}, {'MD_code': 'MD191100', 'Qty': 0.0640021504}, {'MD_code': 'MD191103', 'Qty': 0.191999968}, {'MD_code': 'MD191131', 'Qty': 0.9792030784000001}, {'MD_code': 'MD191146', 'Qty': 2.2399974656}, {'MD_code': 'MD191073', 'Qty': 3.2000010240000005}, {'MD_code': 'MD191074', 'Qty': 0.319998304}, {'MD_code': 'MD191079', 'Qty': 0.639996608}, {'MD_code': 'MD191172', 'Qty': 2.5600044160000004}, {'MD_code': 'MD191266', 'Qty': 2.271999648}, {'MD_code': 'MD191038', 'Qty': 3.06399852}, {'MD_code': 'MD191095', 'Qty': 0.5360014}, {'MD_code': 'MD191100', 'Qty': 0.06800024}, {'MD_code': 'MD191103', 'Qty': 0.11599918}, {'MD_code': 'MD191127', 'Qty': 0.37599936}, {'MD_code': 'MD191130', 'Qty': 0.0200013}, {'MD_code': 'MD191073', 'Qty': 2.3720021919999996}, {'MD_code': 'MD191079', 'Qty': 0.5360012}, {'MD_code': 'MD191085', 'Qty': 0.8800016959999998}, {'MD_code': 'MD191172', 'Qty': 0.803999504}, {'MD_code': 'MD191099', 'Qty': 30.700697663999996}, {'MD_code': 'MD191100', 'Qty': 23.025523248}, {'MD_code': 'MD191103', 'Qty': 51.1679309232}, {'MD_code': 'MD191130', 'Qty': 46.05135094559999}, {'MD_code': 'MD191194', 'Qty': 153.5040972192}, {'MD_code': 'MD191005', 'Qty': 255.83984649600004}, {'MD_code': 'MD191057', 'Qty': 102.33571857600002}, {'MD_code': 'MD191067', 'Qty': 102.33571857600002}, {'MD_code': 'MD191087', 'Qty': 307.00825584}, {'MD_code': 'MD191104', 'Qty': 204.67253726400003}, {'MD_code': 'MD191159', 'Qty': 127.91992324800002}, {'MD_code': 'MD191007', 'Qty': 104.37852945600001}, {'MD_code': 'MD191015', 'Qty': 54.8397353056}, {'MD_code': 'MD191117', 'Qty': 135.45487165760002}, {'MD_code': 'MD191130', 'Qty': 127.9602383712}, {'MD_code': 'MD191133', 'Qty': 219.3602252096}, {'MD_code': 'MD191001', 'Qty': 146.2399279768}, {'MD_code': 'MD191057', 'Qty': 48.62453000440001}, {'MD_code': 'MD191110', 'Qty': 63.98026140400001}, {'MD_code': 'MD191120', 'Qty': 522.2596806148}, {'MD_code': 'MD191001', 'Qty': 30.09039072}, {'MD_code': 'MD191100', 'Qty': 11.600078880000002}, {'MD_code': 'MD191110', 'Qty': 10.439944319999999}, {'MD_code': 'MD191115', 'Qty': 11.600078880000002}, {'MD_code': 'MD191120', 'Qty': 66.23606496000001}, {'MD_code': 'MD191130', 'Qty': 11.600078880000002}, {'MD_code': 'MD191133', 'Qty': 34.75354896}, {'MD_code': 'MD191268', 'Qty': 4.6399953599999995}, {'MD_code': 'MD191100', 'Qty': 555.8778}, {'MD_code': 'MD191183', 'Qty': 244.5222}, {'MD_code': 'MD191100', 'Qty': 183.839564912}, {'MD_code': 'MD191117', 'Qty': 76.59965683200001}, {'MD_code': 'MD191120', 'Qty': 643.440419768}, {'MD_code': 'MD191145', 'Qty': 36.76810724}, {'MD_code': 'MD191190', 'Qty': 30.640251248}, {'MD_code': 'MD191099', 'Qty': 17.1791692206}, {'MD_code': 'MD191103', 'Qty': 28.631948701}, {'MD_code': 'MD191130', 'Qty': 22.6669464343}, {'MD_code': 'MD191194', 'Qty': 83.2714192073}, {'MD_code': 'MD191254', 'Qty': 3.6982609889000004}, {'MD_code': 'MD191080', 'Qty': 59.649960034500005}, {'MD_code': 'MD191087', 'Qty': 86.25396203599999}, {'MD_code': 'MD191120', 'Qty': 47.7199206655}, {'MD_code': 'MD191159', 'Qty': 43.18665726399999}, {'MD_code': 'MD191039', 'Qty': 11.757805695}, {'MD_code': 'MD191095', 'Qty': 70.544929455}, {'MD_code': 'MD191103', 'Qty': 117.57519987750003}, {'MD_code': 'MD191113', 'Qty': 352.724647275}, {'MD_code': 'MD191130', 'Qty': 117.57519987750003}, {'MD_code': 'MD191160', 'Qty': 282.17971782}, {'MD_code': 'MD191041', 'Qty': 705.4492945500001}, {'MD_code': 'MD191046', 'Qty': 47.029952970000004}, {'MD_code': 'MD191074', 'Qty': 705.4492945500001}, {'MD_code': 'MD191172', 'Qty': 352.72464727500005}, {'MD_code': 'MD191039', 'Qty': 0.19438561440000002}, {'MD_code': 'MD191073', 'Qty': 9.7199965008}, {'MD_code': 'MD191085', 'Qty': 5.1839913168}, {'MD_code': 'MD191097', 'Qty': 5.1839913168}, {'MD_code': 'MD191103', 'Qty': 1.9439924832000002}, {'MD_code': 'MD191131', 'Qty': 6.479997667199999}, {'MD_code': 'MD191170', 'Qty': 0.19438561440000002}, {'MD_code': 'MD191172', 'Qty': 5.1839913168}, {'MD_code': 'MD191038', 'Qty': 19.440030132000004}, {'MD_code': 'MD191074', 'Qty': 10.368028836}, {'MD_code': 'MD191095', 'Qty': 6.480010044}, {'MD_code': 'MD191109', 'Qty': 2.591991252}, {'MD_code': 'MD191130', 'Qty': 0.971972784}, {'MD_code': 'MD191139', 'Qty': 2.591991252}, {'MD_code': 'MD191141', 'Qty': 11.663992548000001}, {'MD_code': 'MD191160', 'Qty': 9.719983152000001}, {'MD_code': 'MD191073', 'Qty': 12.370039583999999}, {'MD_code': 'MD191085', 'Qty': 9.896059376000002}, {'MD_code': 'MD191097', 'Qty': 12.370039583999999}, {'MD_code': 'MD191103', 'Qty': 2.4739802080000004}, {'MD_code': 'MD191146', 'Qty': 74.219960416}, {'MD_code': 'MD191170', 'Qty': 2.4739802080000004}, {'MD_code': 'MD191172', 'Qty': 24.739940624}, {'MD_code': 'MD191095', 'Qty': 12.369992578000002}, {'MD_code': 'MD191109', 'Qty': 4.948039584000001}, {'MD_code': 'MD191130', 'Qty': 2.4740197920000004}, {'MD_code': 'MD191131', 'Qty': 61.84996289}, {'MD_code': 'MD191139', 'Qty': 4.948039584000001}, {'MD_code': 'MD191160', 'Qty': 19.792051954}, {'MD_code': 'MD191095', 'Qty': 10.132495271500002}, {'MD_code': 'MD191109', 'Qty': 5.133795136400001}, {'MD_code': 'MD191110', 'Qty': 0.6754935152}, {'MD_code': 'MD191130', 'Qty': 2.5668975682000004}, {'MD_code': 'MD191073', 'Qty': 63.422880087}, {'MD_code': 'MD191074', 'Qty': 29.8858021301}, {'MD_code': 'MD191079', 'Qty': 10.1422145006}, {'MD_code': 'MD191172', 'Qty': 16.6332935433}, {'MD_code': 'MD191266', 'Qty': 20.284569370099998}, {'MD_code': 'MD191039', 'Qty': 6.7219132862}, {'MD_code': 'MD191041', 'Qty': 150.9088838672}, {'MD_code': 'MD191087', 'Qty': 18.8215455518}, {'MD_code': 'MD191097', 'Qty': 20.166053776000002}, {'MD_code': 'MD191103', 'Qty': 10.083026888000001}, {'MD_code': 'MD191127', 'Qty': 53.44004250639999}, {'MD_code': 'MD191190', 'Qty': 13.4441404898}, {'MD_code': 'MD191266', 'Qty': 40.332107552000004}, {'MD_code': 'MD191038', 'Qty': 150.9087326222}, {'MD_code': 'MD191095', 'Qty': 66.8840236848}, {'MD_code': 'MD191130', 'Qty': 3.3611519172}, {'MD_code': 'MD191141', 'Qty': 83.6890398176}, {'MD_code': 'MD191189', 'Qty': 66.8840236848}, {'MD_code': 'MD191038', 'Qty': 154.32993675}, {'MD_code': 'MD191058', 'Qty': 6.3250506}, {'MD_code': 'MD191141', 'Qty': 55.660012650000006}, {'MD_code': 'MD191131', 'Qty': 193.544889945}, {'MD_code': 'MD191265', 'Qty': 70.840110055}, {'MD_code': 'MD191057', 'Qty': 14.8223867904}, {'MD_code': 'MD191110', 'Qty': 11.520054528}, {'MD_code': 'MD191268', 'Qty': 105.29275868159999}, {'MD_code': 'MD191059', 'Qty': 56.15755}, {'MD_code': 'MD191168', 'Qty': 56.15755}, {'MD_code': 'MD191090', 'Qty': 122.72844143999997}, {'MD_code': 'MD191096', 'Qty': 16.357682879999995}, {'MD_code': 'MD191112', 'Qty': 9.82835568}, {'MD_code': 'MD191124', 'Qty': 45.81984}, {'MD_code': 'MD191131', 'Qty': 34.36487999999999}, {'MD_code': 'MD191124', 'Qty': 96.06218799999999}, {'MD_code': 'MD191132', 'Qty': 47.314212}, {'MD_code': 'MD191059', 'Qty': 6.6960098208000005}, {'MD_code': 'MD191168', 'Qty': 20.534390179200003}, {'MD_code': 'MD191124', 'Qty': 99.54715535999998}, {'MD_code': 'MD191225', 'Qty': 34.37284464}, {'MD_code': 'MD191071', 'Qty': 8.068016135999999}, {'MD_code': 'MD191124', 'Qty': 40.339983864}, {'MD_code': 'MD191112', 'Qty': 3.216001608}, {'MD_code': 'MD191225', 'Qty': 1.6079983919999998}, {'MD_code': 'MD191110', 'Qty': 3.6149694894}, {'MD_code': 'MD191115', 'Qty': 40.9700239554}, {'MD_code': 'MD191130', 'Qty': 65.06994379880001}, {'MD_code': 'MD191268', 'Qty': 13.592339508999999}, {'MD_code': 'MD191057', 'Qty': 211.4953471384}, {'MD_code': 'MD191099', 'Qty': 126.89685500179999}, {'MD_code': 'MD191111', 'Qty': 194.5758253517}, {'MD_code': 'MD191115', 'Qty': 145.5085939281}, {'MD_code': 'MD191130', 'Qty': 204.7273617831}, {'MD_code': 'MD191080', 'Qty': 76.1381238618}, {'MD_code': 'MD191087', 'Qty': 359.54160997739996}, {'MD_code': 'MD191120', 'Qty': 33.8391661608}, {'MD_code': 'MD191071', 'Qty': 600.0407045952}, {'MD_code': 'MD191080', 'Qty': 166.1656431072}, {'MD_code': 'MD191087', 'Qty': 784.669738512}, {'MD_code': 'MD191120', 'Qty': 73.85193851199999}, {'MD_code': 'MD191057', 'Qty': 950.095688}, {'MD_code': 'MD191099', 'Qty': 276.9425908096}, {'MD_code': 'MD191103', 'Qty': 16.6163722976}, {'MD_code': 'MD191111', 'Qty': 381.8102608928}, {'MD_code': 'MD191115', 'Qty': 265.4956548096}, {'MD_code': 'MD191130', 'Qty': 398.4266331904}, {'MD_code': 'MD191010', 'Qty': 62.78}, {'MD_code': 'MD191100', 'Qty': 1757.8400000000001}, {'MD_code': 'MD191117', 'Qty': 313.90000000000003}, {'MD_code': 'MD191120', 'Qty': 62.78}, {'MD_code': 'MD191189', 'Qty': 941.6999999999999}, {'MD_code': 'MD191007', 'Qty': 108.92702399999999}, {'MD_code': 'MD191099', 'Qty': 21.7854048}, {'MD_code': 'MD191100', 'Qty': 19.969954400000002}, {'MD_code': 'MD191103', 'Qty': 36.309008}, {'MD_code': 'MD191130', 'Qty': 39.939908800000005}, {'MD_code': 'MD191005', 'Qty': 145.235854764}, {'MD_code': 'MD191067', 'Qty': 54.4634455365}, {'MD_code': 'MD191087', 'Qty': 145.235854764}, {'MD_code': 'MD191104', 'Qty': 72.617927382}, {'MD_code': 'MD191159', 'Qty': 72.617927382}, {'MD_code': 'MD191007', 'Qty': 81.429024}, {'MD_code': 'MD191099', 'Qty': 16.2858048}, {'MD_code': 'MD191100', 'Qty': 14.928654400000001}, {'MD_code': 'MD191103', 'Qty': 27.143008000000002}, {'MD_code': 'MD191130', 'Qty': 29.857308800000002}, {'MD_code': 'MD191005', 'Qty': 108.571891428}, {'MD_code': 'MD191067', 'Qty': 40.7144592855}, {'MD_code': 'MD191087', 'Qty': 108.571891428}, {'MD_code': 'MD191104', 'Qty': 54.285945714}, {'MD_code': 'MD191159', 'Qty': 54.285945714}, {'MD_code': 'MD191057', 'Qty': 590.6538659423999}, {'MD_code': 'MD191099', 'Qty': 482.36843900959997}, {'MD_code': 'MD191111', 'Qty': 905.6707479872}, {'MD_code': 'MD191115', 'Qty': 787.5384879232}, {'MD_code': 'MD191130', 'Qty': 950.9535419488}, {'MD_code': 'MD191087', 'Qty': 1673.5215943290002}, {'MD_code': 'MD191120', 'Qty': 157.508905671}, {'MD_code': 'MD191021', 'Qty': 0.0}, {'MD_code': 'MD191022', 'Qty': 0.0}, {'MD_code': 'MD191023', 'Qty': 0.0}, {'MD_code': 'MD191099', 'Qty': 0.0}, {'MD_code': 'MD191131', 'Qty': 0.0}, {'MD_code': 'MD191071', 'Qty': 64.66540017000001}, {'MD_code': 'MD191090', 'Qty': 0.61559983}, {'MD_code': 'MD191031', 'Qty': 1.5250061}, {'MD_code': 'MD191035', 'Qty': 10.980043919999998}, {'MD_code': 'MD191036', 'Qty': 12.2000488}, {'MD_code': 'MD191127', 'Qty': 24.39998902}, {'MD_code': 'MD191145', 'Qty': 3.0500122}, {'MD_code': 'MD191172', 'Qty': 4.5750183}, {'MD_code': 'MD191208', 'Qty': 30.500013420000002}, {'MD_code': 'MD191209', 'Qty': 12.2000488}, {'MD_code': 'MD191211', 'Qty': 9.1500366}, {'MD_code': 'MD191073', 'Qty': 18.410014202000003}, {'MD_code': 'MD191079', 'Qty': 5.25997896}, {'MD_code': 'MD191087', 'Qty': 21.040003682000002}, {'MD_code': 'MD191097', 'Qty': 5.25997896}, {'MD_code': 'MD191098', 'Qty': 23.143995266}, {'MD_code': 'MD191109', 'Qty': 1.577993688}, {'MD_code': 'MD191146', 'Qty': 13.150035242}, {'MD_code': 'MD191095', 'Qty': 9.205019199}, {'MD_code': 'MD191103', 'Qty': 3.6819842200000004}, {'MD_code': 'MD191127', 'Qty': 28.666986061000003}, {'MD_code': 'MD191130', 'Qty': 1.315027878}, {'MD_code': 'MD191131', 'Qty': 15.779982642000002}, {'MD_code': 'MD191038', 'Qty': 1.46999853}, {'MD_code': 'MD191095', 'Qty': 0.8399984249999999}, {'MD_code': 'MD191100', 'Qty': 0.041998635}, {'MD_code': 'MD191103', 'Qty': 0.12600104999999998}, {'MD_code': 'MD191113', 'Qty': 1.8900003149999998}, {'MD_code': 'MD191130', 'Qty': 0.10499915999999998}, {'MD_code': 'MD191131', 'Qty': 0.6300001049999999}, {'MD_code': 'MD191170', 'Qty': 0.041998635}, {'MD_code': 'MD191017', 'Qty': 0.630000252}, {'MD_code': 'MD191074', 'Qty': 1.0500004200000002}, {'MD_code': 'MD191079', 'Qty': 0.8400003359999999}, {'MD_code': 'MD191085', 'Qty': 0.8400003359999999}, {'MD_code': 'MD191127', 'Qty': 1.0500004200000002}, {'MD_code': 'MD191146', 'Qty': 1.0500004200000002}, {'MD_code': 'MD191190', 'Qty': 0.125997816}, {'MD_code': 'MD191095', 'Qty': 0.6299993700000001}, {'MD_code': 'MD191103', 'Qty': 0.125999874}, {'MD_code': 'MD191130', 'Qty': 0.105000672}, {'MD_code': 'MD191131', 'Qty': 0.6299993700000001}, {'MD_code': 'MD191170', 'Qty': 0.063000714}, {'MD_code': 'MD191017', 'Qty': 0.630002016}, {'MD_code': 'MD191074', 'Qty': 1.0499975639999999}, {'MD_code': 'MD191079', 'Qty': 0.630002016}, {'MD_code': 'MD191080', 'Qty': 0.251998488}, {'MD_code': 'MD191085', 'Qty': 0.840002688}, {'MD_code': 'MD191087', 'Qty': 0.168002856}, {'MD_code': 'MD191127', 'Qty': 1.0499975639999999}, {'MD_code': 'MD191146', 'Qty': 1.0499975639999999}, {'MD_code': 'MD191190', 'Qty': 0.125999244}, {'MD_code': 'MD191038', 'Qty': 4.7039949824}, {'MD_code': 'MD191046', 'Qty': 0.1887991168}, {'MD_code': 'MD191073', 'Qty': 1.5680018815999999}, {'MD_code': 'MD191095', 'Qty': 0.3775982336}, {'MD_code': 'MD191103', 'Qty': 0.6272050175999999}, {'MD_code': 'MD191113', 'Qty': 0.6272050175999999}, {'MD_code': 'MD191127', 'Qty': 1.5680018815999999}, {'MD_code': 'MD191130', 'Qty': 0.124803392}, {'MD_code': 'MD191172', 'Qty': 0.31360250879999996}, {'MD_code': 'MD191189', 'Qty': 0.5631986304}, {'MD_code': 'MD191095', 'Qty': 91.096239127}, {'MD_code': 'MD191103', 'Qty': 34.160783646999995}, {'MD_code': 'MD191127', 'Qty': 341.60979503399994}, {'MD_code': 'MD191130', 'Qty': 22.774182192}, {'MD_code': 'MD191073', 'Qty': 421.31866749960005}, {'MD_code': 'MD191080', 'Qty': 36.4384296062}, {'MD_code': 'MD191085', 'Qty': 182.192148031}, {'MD_code': 'MD191091', 'Qty': 91.0955832358}, {'MD_code': 'MD191131', 'Qty': 250.513590068}, {'MD_code': 'MD191049', 'Qty': 0.19999680000000003}, {'MD_code': 'MD191222', 'Qty': 6.3999972000000005}, {'MD_code': 'MD191226', 'Qty': 10.000006}, {'MD_code': 'MD191095', 'Qty': 5.400003}, {'MD_code': 'MD191103', 'Qty': 5.600007}, {'MD_code': 'MD191226', 'Qty': 9.99999}, {'MD_code': 'MD191112', 'Qty': 6.5}, {'MD_code': 'MD191133', 'Qty': 6.5}, {'MD_code': 'MD191194', 'Qty': 0.560994687}, {'MD_code': 'MD191269', 'Qty': 13.200005313}, {'MD_code': 'MD191095', 'Qty': 0.0}, {'MD_code': 'MD191109', 'Qty': 0.0}, {'MD_code': 'MD191127', 'Qty': 0.0}, {'MD_code': 'MD191172', 'Qty': 0.0}, {'MD_code': 'MD191073', 'Qty': 0.0}, {'MD_code': 'MD191079', 'Qty': 0.0}, {'MD_code': 'MD191087', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191100', 'Qty': 1.0150007349999999}, {'MD_code': 'MD191110', 'Qty': 0.26250049}, {'MD_code': 'MD191133', 'Qty': 1.0150007349999999}, {'MD_code': 'MD191268', 'Qty': 0.192500525}, {'MD_code': 'MD191091', 'Qty': 58.104085575}, {'MD_code': 'MD191095', 'Qty': 62.946047820900006}, {'MD_code': 'MD191103', 'Qty': 19.368118295699997}, {'MD_code': 'MD191130', 'Qty': 7.2630780248999995}, {'MD_code': 'MD191190', 'Qty': 0.5809061997}, {'MD_code': 'MD191217', 'Qty': 121.05013339589999}, {'MD_code': 'MD191038', 'Qty': 169.47014526}, {'MD_code': 'MD191113', 'Qty': 48.41995158}, {'MD_code': 'MD191141', 'Qty': 96.83990316}, {'MD_code': 'MD191038', 'Qty': 20.397957508}, {'MD_code': 'MD191098', 'Qty': 5.1597094864}, {'MD_code': 'MD191103', 'Qty': 1.0955771856}, {'MD_code': 'MD191113', 'Qty': 1.0955771856}, {'MD_code': 'MD191170', 'Qty': 0.005606388800000001}, {'MD_code': 'MD191055', 'Qty': 1.0988707554}, {'MD_code': 'MD191073', 'Qty': 5.152141021299999}, {'MD_code': 'MD191080', 'Qty': 1.0988707554}, {'MD_code': 'MD191127', 'Qty': 8.271073605500002}, {'MD_code': 'MD191131', 'Qty': 5.4811438624}, {'MD_code': 'MD191095', 'Qty': 245.3056548}, {'MD_code': 'MD191098', 'Qty': 102.34089420000001}, {'MD_code': 'MD191103', 'Qty': 60.9357996}, {'MD_code': 'MD191130', 'Qty': 24.9993024}, {'MD_code': 'MD191131', 'Qty': 245.3056548}, {'MD_code': 'MD191146', 'Qty': 102.34089420000001}, {'MD_code': 'MD191073', 'Qty': 1431.56856843}, {'MD_code': 'MD191091', 'Qty': 245.411754588}, {'MD_code': 'MD191127', 'Qty': 409.01959098000003}, {'MD_code': 'MD191146', 'Qty': 613.52938647}, {'MD_code': 'MD191266', 'Qty': 449.921550078}, {'MD_code': 'MD191038', 'Qty': 112.9202348736}, {'MD_code': 'MD191041', 'Qty': 141.1498060599}, {'MD_code': 'MD191079', 'Qty': 21.1725440388}, {'MD_code': 'MD191095', 'Qty': 39.5217896865}, {'MD_code': 'MD191098', 'Qty': 14.1150293592}, {'MD_code': 'MD191103', 'Qty': 5.646109250099999}, {'MD_code': 'MD191127', 'Qty': 18.9142953516}, {'MD_code': 'MD191130', 'Qty': 7.0575146796}, {'MD_code': 'MD191141', 'Qty': 76.220768514}, {'MD_code': 'MD191266', 'Qty': 50.81400818670001}, {'MD_code': 'MD191085', 'Qty': 0.0}, {'MD_code': 'MD191091', 'Qty': 0.0}, {'MD_code': 'MD191146', 'Qty': 0.0}, {'MD_code': 'MD191074', 'Qty': 0.0}, {'MD_code': 'MD191095', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191139', 'Qty': 0.0}, {'MD_code': 'MD191041', 'Qty': 0.0}, {'MD_code': 'MD191079', 'Qty': 0.0}, {'MD_code': 'MD191087', 'Qty': 0.0}, {'MD_code': 'MD191095', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.0}, {'MD_code': 'MD191109', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191141', 'Qty': 0.0}, {'MD_code': 'MD191237', 'Qty': 0.0}, {'MD_code': 'MD191038', 'Qty': 364.2517818}, {'MD_code': 'MD191103', 'Qty': 6.584752439999999}, {'MD_code': 'MD191127', 'Qty': 412.43544647999994}, {'MD_code': 'MD191130', 'Qty': 6.898312079999999}, {'MD_code': 'MD191141', 'Qty': 94.06789199999999}, {'MD_code': 'MD191262', 'Qty': 160.96061519999998}, {'MD_code': 'MD191095', 'Qty': 2.9202716235000006}, {'MD_code': 'MD191103', 'Qty': 2.7549972449999998}, {'MD_code': 'MD191130', 'Qty': 1.1019988980000002}, {'MD_code': 'MD191131', 'Qty': 55.100008540500006}, {'MD_code': 'MD191170', 'Qty': 1.763223693}, {'MD_code': 'MD191073', 'Qty': 38.019028927499996}, {'MD_code': 'MD191085', 'Qty': 2.7550294785000005}, {'MD_code': 'MD191146', 'Qty': 19.285017411600002}, {'MD_code': 'MD191190', 'Qty': 2.9202871617}, {'MD_code': 'MD191095', 'Qty': 0.5460048594}, {'MD_code': 'MD191103', 'Qty': 0.45499574119999997}, {'MD_code': 'MD191130', 'Qty': 0.18200161979999996}, {'MD_code': 'MD191131', 'Qty': 9.099997906999999}, {'MD_code': 'MD191141', 'Qty': 1.5105984893999997}, {'MD_code': 'MD191186', 'Qty': 4.823001383199999}, {'MD_code': 'MD191073', 'Qty': 6.3094385717999995}, {'MD_code': 'MD191085', 'Qty': 0.6038993688}, {'MD_code': 'MD191097', 'Qty': 0.36053755919999997}, {'MD_code': 'MD191146', 'Qty': 3.1547140716}, {'MD_code': 'MD191131', 'Qty': 1508.3248017551}, {'MD_code': 'MD191170', 'Qty': 4.4358464097}, {'MD_code': 'MD191262', 'Qty': 532.3506518352}, {'MD_code': 'MD191038', 'Qty': 1384.1096007375}, {'MD_code': 'MD191103', 'Qty': 53.23429019999999}, {'MD_code': 'MD191130', 'Qty': 26.617145099999995}, {'MD_code': 'MD191224', 'Qty': 35.49062107499999}, {'MD_code': 'MD191237', 'Qty': 141.95920147500001}, {'MD_code': 'MD191095', 'Qty': 112.084887915}, {'MD_code': 'MD191103', 'Qty': 44.833955165999996}, {'MD_code': 'MD191109', 'Qty': 44.833955165999996}, {'MD_code': 'MD191130', 'Qty': 44.833955165999996}, {'MD_code': 'MD191055', 'Qty': 269.0033857742}, {'MD_code': 'MD191073', 'Qty': 883.2306428792}, {'MD_code': 'MD191097', 'Qty': 132.2603403506}, {'MD_code': 'MD191146', 'Qty': 773.3862444462001}, {'MD_code': 'MD191172', 'Qty': 358.6719865498}, {'MD_code': 'MD191095', 'Qty': 26.536373463600004}, {'MD_code': 'MD191103', 'Qty': 10.757989242}, {'MD_code': 'MD191130', 'Qty': 3.5859964140000007}, {'MD_code': 'MD191186', 'Qty': 14.343985656000003}, {'MD_code': 'MD191073', 'Qty': 193.6440086064}, {'MD_code': 'MD191079', 'Qty': 29.763684172200005}, {'MD_code': 'MD191127', 'Qty': 35.86010722140001}, {'MD_code': 'MD191094', 'Qty': 3.585992828}, {'MD_code': 'MD191184', 'Qty': 0.896442624}, {'MD_code': 'MD191185', 'Qty': 0.896442624}, {'MD_code': 'MD191240', 'Qty': 192.92681434399998}, {'MD_code': 'MD191241', 'Qty': 24.026307579999997}, {'MD_code': 'MD191095', 'Qty': 1.1131994434}, {'MD_code': 'MD191103', 'Qty': 0.3630006776}, {'MD_code': 'MD191130', 'Qty': 0.241999879}, {'MD_code': 'MD191073', 'Qty': 6.0499996128}, {'MD_code': 'MD191079', 'Qty': 1.1495022627}, {'MD_code': 'MD191085', 'Qty': 2.4200037389}, {'MD_code': 'MD191146', 'Qty': 4.8400074778}, {'MD_code': 'MD191172', 'Qty': 4.8400074778}, {'MD_code': 'MD191190', 'Qty': 0.1693988989}, {'MD_code': 'MD191095', 'Qty': 0.36000022499999995}, {'MD_code': 'MD191103', 'Qty': 0.13499986499999997}, {'MD_code': 'MD191130', 'Qty': 0.08999991}, {'MD_code': 'MD191073', 'Qty': 1.3499984970000003}, {'MD_code': 'MD191079', 'Qty': 0.368997687}, {'MD_code': 'MD191085', 'Qty': 0.9000028800000001}, {'MD_code': 'MD191146', 'Qty': 1.3499984970000003}, {'MD_code': 'MD191172', 'Qty': 1.799999937}, {'MD_code': 'MD191190', 'Qty': 0.054002502}, {'MD_code': 'MD191015', 'Qty': 10.79196435}, {'MD_code': 'MD191059', 'Qty': 8.6058108}, {'MD_code': 'MD191103', 'Qty': 25.8868341}, {'MD_code': 'MD191190', 'Qty': 0.8675212500000001}, {'MD_code': 'MD191217', 'Qty': 21.514527}, {'MD_code': 'MD191268', 'Qty': 1.7350425000000003}, {'MD_code': 'MD191007', 'Qty': 0.0200997135}, {'MD_code': 'MD191100', 'Qty': 0.3020996757}, {'MD_code': 'MD191110', 'Qty': 0.030000269700000002}, {'MD_code': 'MD191120', 'Qty': 0.3020996757}, {'MD_code': 'MD191268', 'Qty': 0.0227999883}, {'MD_code': 'MD191049', 'Qty': 14.5408983984}, {'MD_code': 'MD191057', 'Qty': 112.532086794}, {'MD_code': 'MD191103', 'Qty': 80.9215228716}, {'MD_code': 'MD191204', 'Qty': 44.8861039056}, {'MD_code': 'MD191221', 'Qty': 132.12954459120002}, {'MD_code': 'MD191224', 'Qty': 589.8422434391999}, {'MD_code': 'MD191017', 'Qty': 0.81}, {'MD_code': 'MD191049', 'Qty': 0.21599913599999998}, {'MD_code': 'MD191079', 'Qty': 0.21599913599999998}, {'MD_code': 'MD191189', 'Qty': 1.349999136}, {'MD_code': 'MD191049', 'Qty': 23.541137529}, {'MD_code': 'MD191079', 'Qty': 28.910051625}, {'MD_code': 'MD191221', 'Qty': 371.700154462}, {'MD_code': 'MD191222', 'Qty': 21.476102011000002}, {'MD_code': 'MD191095', 'Qty': 62.775746418}, {'MD_code': 'MD191103', 'Qty': 61.949799282}, {'MD_code': 'MD191221', 'Qty': 412.999916574}, {'MD_code': 'MD191038', 'Qty': 2845.572102912}, {'MD_code': 'MD191079', 'Qty': 533.544769296}, {'MD_code': 'MD191095', 'Qty': 995.94286458}, {'MD_code': 'MD191098', 'Qty': 355.696512864}, {'MD_code': 'MD191103', 'Qty': 142.281062292}, {'MD_code': 'MD191127', 'Qty': 476.637258672}, {'MD_code': 'MD191130', 'Qty': 177.848256432}, {'MD_code': 'MD191141', 'Qty': 1920.75134088}, {'MD_code': 'MD191262', 'Qty': 3556.9528429079996}, {'MD_code': 'MD191266', 'Qty': 1280.504989164}, {'MD_code': 'MD191055', 'Qty': 3.054996945}, {'MD_code': 'MD191073', 'Qty': 48.880006720999994}, {'MD_code': 'MD191103', 'Qty': 3.6659963339999995}, {'MD_code': 'MD191095', 'Qty': 9.7760442975}, {'MD_code': 'MD191127', 'Qty': 73.3200039715}, {'MD_code': 'MD191130', 'Qty': 0.916501222}, {'MD_code': 'MD191139', 'Qty': 9.7760442975}, {'MD_code': 'MD191095', 'Qty': 1.643998356}, {'MD_code': 'MD191103', 'Qty': 4.110001644}, {'MD_code': 'MD191170', 'Qty': 0.822001644}, {'MD_code': 'MD191172', 'Qty': 4.109998356}, {'MD_code': 'MD191095', 'Qty': 1.0780366032000002}, {'MD_code': 'MD191100', 'Qty': 0.04990937040000001}, {'MD_code': 'MD191130', 'Qty': 0.18965402640000004}, {'MD_code': 'MD191039', 'Qty': 0.2159937107}, {'MD_code': 'MD191100', 'Qty': 0.13391606020000002}, {'MD_code': 'MD191109', 'Qty': 0.3239902291}, {'MD_code': 'MD191073', 'Qty': 7.560010365}, {'MD_code': 'MD191074', 'Qty': 2.868489524}, {'MD_code': 'MD191079', 'Qty': 0.7560010365}, {'MD_code': 'MD191085', 'Qty': 1.0799949285}, {'MD_code': 'MD191172', 'Qty': 3.024004146}, {'MD_code': 'MD191073', 'Qty': 6.156000809999999}, {'MD_code': 'MD191074', 'Qty': 1.619999595}, {'MD_code': 'MD191079', 'Qty': 0.56700162}, {'MD_code': 'MD191085', 'Qty': 0.8100056699999999}, {'MD_code': 'MD191103', 'Qty': 0.32399756999999996}, {'MD_code': 'MD191172', 'Qty': 2.2679947350000003}, {'MD_code': 'MD191038', 'Qty': 1.2959995788}, {'MD_code': 'MD191095', 'Qty': 0.8100000648000001}, {'MD_code': 'MD191100', 'Qty': 0.1376996436}, {'MD_code': 'MD191109', 'Qty': 0.2430010692}, {'MD_code': 'MD191130', 'Qty': 0.1376996436}, {'MD_code': 'MD191057', 'Qty': 130.999869}, {'MD_code': 'MD191073', 'Qty': 52.399869}, {'MD_code': 'MD191098', 'Qty': 10.480131}, {'MD_code': 'MD191100', 'Qty': 6.288}, {'MD_code': 'MD191103', 'Qty': 65.500131}, {'MD_code': 'MD191130', 'Qty': 3.144}, {'MD_code': 'MD191168', 'Qty': 5.239869}, {'MD_code': 'MD191189', 'Qty': 96.940131}, {'MD_code': 'MD191244', 'Qty': 5.239869}, {'MD_code': 'MD191245', 'Qty': 16.768131}, {'MD_code': 'MD191091', 'Qty': 475.72380000000004}, {'MD_code': 'MD191095', 'Qty': 475.72380000000004}, {'MD_code': 'MD191098', 'Qty': 1145.2622333580002}, {'MD_code': 'MD191103', 'Qty': 105.715342836}, {'MD_code': 'MD191127', 'Qty': 264.293114328}, {'MD_code': 'MD191130', 'Qty': 114.525747612}, {'MD_code': 'MD191190', 'Qty': 132.146557164}, {'MD_code': 'MD191262', 'Qty': 722.396104776}, {'MD_code': 'MD191266', 'Qty': 1321.456057164}, {'MD_code': 'MD191007', 'Qty': 1.197}, {'MD_code': 'MD191117', 'Qty': 1.6590036960000003}, {'MD_code': 'MD191130', 'Qty': 2.099997648}, {'MD_code': 'MD191133', 'Qty': 4.619998656000001}, {'MD_code': 'MD191001', 'Qty': 1.6800000000000002}, {'MD_code': 'MD191110', 'Qty': 0.735}, {'MD_code': 'MD191120', 'Qty': 5.985}, {'MD_code': 'MD191073', 'Qty': 534.718823616}, {'MD_code': 'MD191087', 'Qty': 320.831839584}, {'MD_code': 'MD191095', 'Qty': 280.72751875200004}, {'MD_code': 'MD191103', 'Qty': 106.944855552}, {'MD_code': 'MD191127', 'Qty': 695.1361069440001}, {'MD_code': 'MD191130', 'Qty': 66.84053472000001}, {'MD_code': 'MD191141', 'Qty': 534.718823616}, {'MD_code': 'MD191237', 'Qty': 187.15077014400003}, {'MD_code': 'MD191079', 'Qty': 147.047492016}, {'MD_code': 'MD191085', 'Qty': 267.36045451200005}, {'MD_code': 'MD191127', 'Qty': 668.4000534720001}, {'MD_code': 'MD191091', 'Qty': 194.6808}, {'MD_code': 'MD191095', 'Qty': 194.6808}, {'MD_code': 'MD191098', 'Qty': 468.676504728}, {'MD_code': 'MD191103', 'Qty': 43.261967375999994}, {'MD_code': 'MD191127', 'Qty': 108.156865248}, {'MD_code': 'MD191130', 'Qty': 46.867455791999994}, {'MD_code': 'MD191190', 'Qty': 54.078432624}, {'MD_code': 'MD191262', 'Qty': 295.626688416}, {'MD_code': 'MD191266', 'Qty': 540.7804326239999}, {'MD_code': 'MD191095', 'Qty': 1.236625488}, {'MD_code': 'MD191103', 'Qty': 1.0479897792000001}, {'MD_code': 'MD191130', 'Qty': 0.4977949536000001}, {'MD_code': 'MD191141', 'Qty': 0.7859904192}, {'MD_code': 'MD191170', 'Qty': 0.2619955296}, {'MD_code': 'MD191055', 'Qty': 6.287978278400001}, {'MD_code': 'MD191073', 'Qty': 13.0999777664}, {'MD_code': 'MD191079', 'Qty': 1.2366332288000002}, {'MD_code': 'MD191109', 'Qty': 0.49781817600000006}, {'MD_code': 'MD191146', 'Qty': 8.383984192000002}, {'MD_code': 'MD191172', 'Qty': 9.9560083584}, {'MD_code': 'MD191095', 'Qty': 1.1809676834999998}, {'MD_code': 'MD191103', 'Qty': 0.4636043485}, {'MD_code': 'MD191130', 'Qty': 0.5563236195}, {'MD_code': 'MD191170', 'Qty': 0.4636043485}, {'MD_code': 'MD191055', 'Qty': 5.831610024}, {'MD_code': 'MD191073', 'Qty': 15.7380045228}, {'MD_code': 'MD191079', 'Qty': 1.1712170328}, {'MD_code': 'MD191109', 'Qty': 0.4635999435}, {'MD_code': 'MD191146', 'Qty': 8.1447147135}, {'MD_code': 'MD191172', 'Qty': 9.4427945553}, {'MD_code': 'MD191073', 'Qty': 17.5421368463}, {'MD_code': 'MD191079', 'Qty': 0.2103775135}, {'MD_code': 'MD191085', 'Qty': 3.9449778290999995}, {'MD_code': 'MD191095', 'Qty': 2.8141130973999995}, {'MD_code': 'MD191100', 'Qty': 0.47340646979999995}, {'MD_code': 'MD191103', 'Qty': 0.8679118613}, {'MD_code': 'MD191130', 'Qty': 0.8679118613}, {'MD_code': 'MD191146', 'Qty': 40.4230691238}, {'MD_code': 'MD191172', 'Qty': 8.7578675195}, {'MD_code': 'MD191190', 'Qty': 0.18412787799999997}, {'MD_code': 'MD191073', 'Qty': 6.420848788200001}, {'MD_code': 'MD191079', 'Qty': 0.8561195832}, {'MD_code': 'MD191085', 'Qty': 2.1402749151}, {'MD_code': 'MD191095', 'Qty': 1.070149479}, {'MD_code': 'MD191100', 'Qty': 0.1819326243}, {'MD_code': 'MD191103', 'Qty': 0.2140298958}, {'MD_code': 'MD191130', 'Qty': 0.35314211520000005}, {'MD_code': 'MD191146', 'Qty': 12.485357755499999}, {'MD_code': 'MD191190', 'Qty': 0.32104484369999997}, {'MD_code': 'MD191085', 'Qty': 0.0}, {'MD_code': 'MD191095', 'Qty': 0.0}, {'MD_code': 'MD191124', 'Qty': 0.0}, {'MD_code': 'MD191127', 'Qty': 0.0}, {'MD_code': 'MD191131', 'Qty': 0.0}, {'MD_code': 'MD191091', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191172', 'Qty': 0.0}, {'MD_code': 'MD191293', 'Qty': 0.0}, {'MD_code': 'MD191085', 'Qty': 0.0}, {'MD_code': 'MD191095', 'Qty': 0.0}, {'MD_code': 'MD191124', 'Qty': 0.0}, {'MD_code': 'MD191127', 'Qty': 0.0}, {'MD_code': 'MD191091', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191172', 'Qty': 0.0}, {'MD_code': 'MD191293', 'Qty': 0.0}, {'MD_code': 'MD191005', 'Qty': 88.55531897309999}, {'MD_code': 'MD191067', 'Qty': 263.6985781719}, {'MD_code': 'MD191080', 'Qty': 19.6790958849}, {'MD_code': 'MD191100', 'Qty': 4.919671886400001}, {'MD_code': 'MD191103', 'Qty': 1.9677870867}, {'MD_code': 'MD191104', 'Qty': 19.6790958849}, {'MD_code': 'MD191120', 'Qty': 9.839343772800001}, {'MD_code': 'MD191099', 'Qty': 1.2353970961999998}, {'MD_code': 'MD191100', 'Qty': 1.0294994304}, {'MD_code': 'MD191103', 'Qty': 2.4021542362000003}, {'MD_code': 'MD191111', 'Qty': 4.4611530969999995}, {'MD_code': 'MD191130', 'Qty': 1.9731961402000002}, {'MD_code': 'MD191005', 'Qty': 4.2895817841}, {'MD_code': 'MD191080', 'Qty': 6.1769970663}, {'MD_code': 'MD191120', 'Qty': 3.6289811643000003}, {'MD_code': 'MD191159', 'Qty': 3.4745575554}, {'MD_code': 'MD191029', 'Qty': 10.798003308000002}, {'MD_code': 'MD191099', 'Qty': 3.2394177968}, {'MD_code': 'MD191100', 'Qty': 2.6994924248000003}, {'MD_code': 'MD191103', 'Qty': 6.298826860799999}, {'MD_code': 'MD191111', 'Qty': 5.3990184584}, {'MD_code': 'MD191130', 'Qty': 5.174041151200001}, {'MD_code': 'MD191100', 'Qty': 60.687319728599995}, {'MD_code': 'MD191115', 'Qty': 46.6824351357}, {'MD_code': 'MD191225', 'Qty': 359.45511}, {'MD_code': 'MD191268', 'Qty': 46.6824351357}, {'MD_code': 'MD191087', 'Qty': 91.446537457}, {'MD_code': 'MD191120', 'Qty': 211.989562543}, {'MD_code': 'MD191099', 'Qty': 138.979936732}, {'MD_code': 'MD191100', 'Qty': 104.234952549}, {'MD_code': 'MD191103', 'Qty': 231.63368729409999}, {'MD_code': 'MD191130', 'Qty': 208.47128332029996}, {'MD_code': 'MD191194', 'Qty': 694.9024401046}, {'MD_code': 'MD191005', 'Qty': 1158.1693050980002}, {'MD_code': 'MD191057', 'Qty': 463.2667260130001}, {'MD_code': 'MD191067', 'Qty': 463.2667260130001}, {'MD_code': 'MD191087', 'Qty': 1389.80515817}, {'MD_code': 'MD191104', 'Qty': 926.5384321570001}, {'MD_code': 'MD191159', 'Qty': 579.0846525490001}, {'MD_code': 'MD191099', 'Qty': 1.199996}, {'MD_code': 'MD191100', 'Qty': 0.899997}, {'MD_code': 'MD191103', 'Qty': 1.9999973}, {'MD_code': 'MD191130', 'Qty': 1.8000058999999997}, {'MD_code': 'MD191194', 'Qty': 6.000003800000001}, {'MD_code': 'MD191005', 'Qty': 9.999994000000001}, {'MD_code': 'MD191057', 'Qty': 3.9999890000000002}, {'MD_code': 'MD191067', 'Qty': 3.9999890000000002}, {'MD_code': 'MD191087', 'Qty': 12.00001}, {'MD_code': 'MD191104', 'Qty': 8.000021}, {'MD_code': 'MD191159', 'Qty': 4.9999970000000005}, {'MD_code': 'MD191099', 'Qty': 0.0}, {'MD_code': 'MD191100', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191194', 'Qty': 0.0}, {'MD_code': 'MD191005', 'Qty': 0.0}, {'MD_code': 'MD191067', 'Qty': 0.0}, {'MD_code': 'MD191087', 'Qty': 0.0}, {'MD_code': 'MD191104', 'Qty': 0.0}, {'MD_code': 'MD191159', 'Qty': 0.0}, {'MD_code': 'MD191029', 'Qty': 2.98003725}, {'MD_code': 'MD191039', 'Qty': 1.490018625}, {'MD_code': 'MD191057', 'Qty': 14.8999851}, {'MD_code': 'MD191099', 'Qty': 1.1920149}, {'MD_code': 'MD191103', 'Qty': 2.98003725}, {'MD_code': 'MD191111', 'Qty': 1.490018625}, {'MD_code': 'MD191141', 'Qty': 13.409966475000001}, {'MD_code': 'MD191150', 'Qty': 0.148951575}, {'MD_code': 'MD191153', 'Qty': 0.148951575}, {'MD_code': 'MD191268', 'Qty': 2.23497765}, {'MD_code': 'MD191303', 'Qty': 59.600040975000006}, {'MD_code': 'MD191005', 'Qty': 20.86001192}, {'MD_code': 'MD191067', 'Qty': 5.959998510000001}, {'MD_code': 'MD191120', 'Qty': 2.9800163900000003}, {'MD_code': 'MD191159', 'Qty': 4.470007450000001}, {'MD_code': 'MD191005', 'Qty': 0.0}, {'MD_code': 'MD191073', 'Qty': 0.0}, {'MD_code': 'MD191095', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191174', 'Qty': 0.0}, {'MD_code': 'MD191074', 'Qty': 0.0}, {'MD_code': 'MD191079', 'Qty': 0.0}, {'MD_code': 'MD191109', 'Qty': 0.0}, {'MD_code': 'MD191111', 'Qty': 0.0}, {'MD_code': 'MD191146', 'Qty': 0.0}, {'MD_code': 'MD191079', 'Qty': 0.0}, {'MD_code': 'MD191085', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.0}, {'MD_code': 'MD191146', 'Qty': 0.0}, {'MD_code': 'MD191190', 'Qty': 0.0}, {'MD_code': 'MD191038', 'Qty': 0.0}, {'MD_code': 'MD191095', 'Qty': 0.0}, {'MD_code': 'MD191127', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191141', 'Qty': 0.0}, {'MD_code': 'MD191079', 'Qty': 0.0}, {'MD_code': 'MD191085', 'Qty': 0.0}, {'MD_code': 'MD191146', 'Qty': 0.0}, {'MD_code': 'MD191190', 'Qty': 0.0}, {'MD_code': 'MD191095', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.0}, {'MD_code': 'MD191127', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191085', 'Qty': 0.0}, {'MD_code': 'MD191100', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.0}, {'MD_code': 'MD191115', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191189', 'Qty': 0.0}, {'MD_code': 'MD191019', 'Qty': 0.0}, {'MD_code': 'MD191027', 'Qty': 0.0}, {'MD_code': 'MD191189', 'Qty': 0.0}, {'MD_code': 'MD191059', 'Qty': 53.70321005199999}, {'MD_code': 'MD191099', 'Qty': 53.70321005199999}, {'MD_code': 'MD191130', 'Qty': 126.58650075099999}, {'MD_code': 'MD191132', 'Qty': 575.392261814}, {'MD_code': 'PX471A', 'Qty': 460.3143173309999}, {'MD_code': 'MD191005', 'Qty': 268.5163925934}, {'MD_code': 'MD191071', 'Qty': 920.6276317488}, {'MD_code': 'MD191080', 'Qty': 153.4379386248}, {'MD_code': 'MD191087', 'Qty': 176.4524571522}, {'MD_code': 'MD191120', 'Qty': 38.3594846562}, {'MD_code': 'MD191172', 'Qty': 122.75093703300003}, {'MD_code': 'MD191189', 'Qty': 99.7334878398}, {'MD_code': 'MD191262', 'Qty': 958.987116405}, {'MD_code': 'MD191269', 'Qty': 191.79742328100002}, {'MD_code': 'MD191073', 'Qty': 61.5999846}, {'MD_code': 'MD191095', 'Qty': 19.7999571}, {'MD_code': 'MD191103', 'Qty': 6.5999857}, {'MD_code': 'MD191127', 'Qty': 50.5999494}, {'MD_code': 'MD191130', 'Qty': 5.5000176}, {'MD_code': 'MD191266', 'Qty': 32.9999285}, {'MD_code': 'MD191091', 'Qty': 19.7999802}, {'MD_code': 'MD191098', 'Qty': 28.599971399999998}, {'MD_code': 'MD191131', 'Qty': 57.2000517}, {'MD_code': 'MD191190', 'Qty': 3.2999967000000003}, {'MD_code': 'MD191017', 'Qty': 34.20001116}, {'MD_code': 'MD191087', 'Qty': 21.60002988}, {'MD_code': 'MD191091', 'Qty': 12.96003528}, {'MD_code': 'MD191266', 'Qty': 18.000010440000004}, {'MD_code': 'MD191095', 'Qty': 11.006717446400001}, {'MD_code': 'MD191103', 'Qty': 4.398035584800001}, {'MD_code': 'MD191109', 'Qty': 4.398035584800001}, {'MD_code': 'MD191130', 'Qty': 4.398035584800001}, {'MD_code': 'MD191055', 'Qty': 55.01043144449999}, {'MD_code': 'MD191073', 'Qty': 117.35058622800001}, {'MD_code': 'MD191079', 'Qty': 11.006739861}, {'MD_code': 'MD191146', 'Qty': 75.906706581}, {'MD_code': 'MD191172', 'Qty': 88.0070358855}, {'MD_code': 'MD191073', 'Qty': 21.1562285436}, {'MD_code': 'MD191079', 'Qty': 1.8659111093999998}, {'MD_code': 'MD191103', 'Qty': 0.7447855572}, {'MD_code': 'MD191172', 'Qty': 14.9312747898}, {'MD_code': 'MD191055', 'Qty': 9.333536522700001}, {'MD_code': 'MD191095', 'Qty': 1.8659024787}, {'MD_code': 'MD191109', 'Qty': 0.7447992461}, {'MD_code': 'MD191130', 'Qty': 0.8702179395}, {'MD_code': 'MD191131', 'Qty': 22.151921026300002}, {'MD_code': 'MD191146', 'Qty': 12.9399227867}, {'MD_code': 'MD191095', 'Qty': 3.1842170872}, {'MD_code': 'MD191103', 'Qty': 1.2710415226}, {'MD_code': 'MD191109', 'Qty': 1.2710415226}, {'MD_code': 'MD191130', 'Qty': 1.4894998676}, {'MD_code': 'MD191055', 'Qty': 14.861918822600002}, {'MD_code': 'MD191073', 'Qty': 33.9738661453}, {'MD_code': 'MD191079', 'Qty': 3.1842137082999997}, {'MD_code': 'MD191146', 'Qty': 21.9784260632}, {'MD_code': 'MD191172', 'Qty': 25.4803747393}, {'MD_code': 'MD191073', 'Qty': 15.8596690408}, {'MD_code': 'MD191079', 'Qty': 1.4865689072}, {'MD_code': 'MD191103', 'Qty': 0.5958270344}, {'MD_code': 'MD191172', 'Qty': 11.895505179999999}, {'MD_code': 'MD191055', 'Qty': 7.1379116248}, {'MD_code': 'MD191095', 'Qty': 1.4865452408}, {'MD_code': 'MD191109', 'Qty': 0.5958464904}, {'MD_code': 'MD191130', 'Qty': 0.5958464904}, {'MD_code': 'MD191131', 'Qty': 17.604658164}, {'MD_code': 'MD191146', 'Qty': 10.2599919896}, {'MD_code': 'MD191095', 'Qty': 5.6144020416}, {'MD_code': 'MD191103', 'Qty': 2.238801392}, {'MD_code': 'MD191109', 'Qty': 2.238801392}, {'MD_code': 'MD191130', 'Qty': 2.6215951744}, {'MD_code': 'MD191055', 'Qty': 27.7123347732}, {'MD_code': 'MD191073', 'Qty': 74.7967132668}, {'MD_code': 'MD191079', 'Qty': 5.614321062}, {'MD_code': 'MD191146', 'Qty': 38.7091956384}, {'MD_code': 'MD191172', 'Qty': 44.8804435464}, {'MD_code': 'MD191073', 'Qty': 28.912268792000003}, {'MD_code': 'MD191079', 'Qty': 2.1705398272000003}, {'MD_code': 'MD191103', 'Qty': 0.8663033004}, {'MD_code': 'MD191172', 'Qty': 17.3454387858}, {'MD_code': 'MD191055', 'Qty': 11.566816738600002}, {'MD_code': 'MD191095', 'Qty': 2.1705705581}, {'MD_code': 'MD191109', 'Qty': 1.1566703383999999}, {'MD_code': 'MD191130', 'Qty': 1.0139002197}, {'MD_code': 'MD191131', 'Qty': 25.589744272700003}, {'MD_code': 'MD191146', 'Qty': 15.1796545498}, {'MD_code': 'MD191095', 'Qty': 2.002210785}, {'MD_code': 'MD191098', 'Qty': 4.80531432}, {'MD_code': 'MD191103', 'Qty': 2.40265716}, {'MD_code': 'MD191170', 'Qty': 1.33480719}, {'MD_code': 'MD191073', 'Qty': 11.1369521535}, {'MD_code': 'MD191079', 'Qty': 1.8561561225}, {'MD_code': 'MD191080', 'Qty': 1.9799050034999999}, {'MD_code': 'MD191190', 'Qty': 0.445471302}, {'MD_code': 'MD191099', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191194', 'Qty': 0.0}, {'MD_code': 'MD191254', 'Qty': 0.0}, {'MD_code': 'MD191080', 'Qty': 0.0}, {'MD_code': 'MD191087', 'Qty': 0.0}, {'MD_code': 'MD191120', 'Qty': 0.0}, {'MD_code': 'MD191159', 'Qty': 0.0}, {'MD_code': 'MD191015', 'Qty': 3.1499585208000003}, {'MD_code': 'MD191100', 'Qty': 36.791960083199996}, {'MD_code': 'MD191110', 'Qty': 6.803975555999999}, {'MD_code': 'MD191115', 'Qty': 3.0239678448}, {'MD_code': 'MD191120', 'Qty': 37.094433516}, {'MD_code': 'MD191130', 'Qty': 4.5360475776}, {'MD_code': 'MD191268', 'Qty': 4.4099610912}, {'MD_code': 'MD191117', 'Qty': 2.2175944560000005}, {'MD_code': 'MD191159', 'Qty': 1.6477987680000004}, {'MD_code': 'MD191189', 'Qty': 5.297608008}, {'MD_code': 'MD191245', 'Qty': 7.468998768000001}, {'MD_code': 'MD191103', 'Qty': 0.223493742}, {'MD_code': 'MD191127', 'Qty': 13.55899851}, {'MD_code': 'MD191130', 'Qty': 0.223493742}, {'MD_code': 'MD191038', 'Qty': 12.665004768000001}, {'MD_code': 'MD191046', 'Qty': 0.372493742}, {'MD_code': 'MD191073', 'Qty': 5.289506854000001}, {'MD_code': 'MD191141', 'Qty': 3.426994636}, {'MD_code': 'MD191074', 'Qty': 0.0}, {'MD_code': 'MD191095', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191038', 'Qty': 0.0}, {'MD_code': 'MD191073', 'Qty': 0.0}, {'MD_code': 'MD191079', 'Qty': 0.0}, {'MD_code': 'MD191085', 'Qty': 0.0}, {'MD_code': 'MD191141', 'Qty': 0.0}, {'MD_code': 'MD191095', 'Qty': 0.0}, {'MD_code': 'MD191098', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.0}, {'MD_code': 'MD191111', 'Qty': 0.0}, {'MD_code': 'MD191127', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191131', 'Qty': 0.0}, {'MD_code': 'MD191073', 'Qty': 0.0}, {'MD_code': 'MD191079', 'Qty': 0.0}, {'MD_code': 'MD191085', 'Qty': 0.0}, {'MD_code': 'MD191097', 'Qty': 0.0}, {'MD_code': 'MD191085', 'Qty': 0.0}, {'MD_code': 'MD191269', 'Qty': 0.0}, {'MD_code': 'MD191276', 'Qty': 0.0}, {'MD_code': 'MD191007', 'Qty': 0.0}, {'MD_code': 'MD191100', 'Qty': 0.0}, {'MD_code': 'MD191133', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 62.86000000000001}, {'MD_code': 'MD191131', 'Qty': 210.58100000000002}, {'MD_code': 'MD191189', 'Qty': 157.15}, {'MD_code': 'MD191217', 'Qty': 94.29}, {'MD_code': 'MD191301', 'Qty': 103.71900000000001}, {'MD_code': 'MD191058', 'Qty': 28.98}, {'MD_code': 'MD191100', 'Qty': 48.300000000000004}, {'MD_code': 'MD191117', 'Qty': 19.32}, {'MD_code': 'MD191130', 'Qty': 24.150000000000002}, {'MD_code': 'MD191057', 'Qty': 39.8027709063}, {'MD_code': 'MD191080', 'Qty': 47.8196426772}, {'MD_code': 'MD191099', 'Qty': 98.4523699188}, {'MD_code': 'MD191100', 'Qty': 63.57214763550001}, {'MD_code': 'MD191103', 'Qty': 12.2361492528}, {'MD_code': 'MD191120', 'Qty': 63.57214763550001}, {'MD_code': 'MD191268', 'Qty': 23.9098213386}, {'MD_code': 'MD191057', 'Qty': 6.3592290648}, {'MD_code': 'MD191080', 'Qty': 18.801125452799997}, {'MD_code': 'MD191100', 'Qty': 24.9943836528}, {'MD_code': 'MD191120', 'Qty': 24.9943836528}, {'MD_code': 'MD191268', 'Qty': 9.400562726399999}, {'MD_code': 'MD191057', 'Qty': 0.0}, {'MD_code': 'MD191058', 'Qty': 0.0}, {'MD_code': 'MD191059', 'Qty': 0.0}, {'MD_code': 'MD191099', 'Qty': 0.0}, {'MD_code': 'MD191111', 'Qty': 0.0}, {'MD_code': 'MD191115', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191289', 'Qty': 0.0}, {'MD_code': 'MD191073', 'Qty': 0.0}, {'MD_code': 'MD191080', 'Qty': 0.0}, {'MD_code': 'MD191087', 'Qty': 0.0}, {'MD_code': 'MD191120', 'Qty': 0.0}, {'MD_code': 'MD191189', 'Qty': 0.0}, {'MD_code': 'MD191217', 'Qty': 0.0}, {'MD_code': 'MD191085', 'Qty': 0.0}, {'MD_code': 'MD191087', 'Qty': 0.0}, {'MD_code': 'MD191091', 'Qty': 0.0}, {'MD_code': 'MD191095', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191262', 'Qty': 0.0}, {'MD_code': 'MD191038', 'Qty': 0.0}, {'MD_code': 'MD191091', 'Qty': 0.0}, {'MD_code': 'MD191095', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191141', 'Qty': 0.0}, {'MD_code': 'MD191262', 'Qty': 0.0}, {'MD_code': 'MD191266', 'Qty': 0.0}, {'MD_code': 'MD191292', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.7799992200000001}, {'MD_code': 'MD191130', 'Qty': 1.5599984400000002}, {'MD_code': 'MD191133', 'Qty': 3.1200023399999997}, {'MD_code': 'MD191005', 'Qty': 0.0}, {'MD_code': 'MD191067', 'Qty': 0.0}, {'MD_code': 'MD191087', 'Qty': 0.0}, {'MD_code': 'MD191099', 'Qty': 0.0}, {'MD_code': 'MD191100', 'Qty': 0.0}, {'MD_code': 'MD191103', 'Qty': 0.0}, {'MD_code': 'MD191111', 'Qty': 0.0}, {'MD_code': 'MD191115', 'Qty': 0.0}, {'MD_code': 'MD191120', 'Qty': 0.0}, {'MD_code': 'MD191130', 'Qty': 0.0}, {'MD_code': 'MD191159', 'Qty': 0.0}, {'MD_code': 'MD191194', 'Qty': 0.0}]

In [89]:
for item in md_items:
    if item.get('MD_code') == 'PX471A':
        print(item)

{'MD_code': 'PX471A', 'Qty': 460.3143173309999}

In [25]:
from datetime import date, datetime

print(date.today())
print(datetime.now().time().isoformat(timespec='seconds'))

2026-06-09
20:12:05

In [27]:
import pandas as pd

In [67]:
df = pd.read_csv('tropolite_verification/Sheet 1-Table 1.csv')

In [68]:
df

,FG_Item,Parent_Item,Child_Item,Child_Name,Qty_Per_FG,UOM,Conversion Factor,Required Qty,QTY_needed,Projected qty,Unnamed: 10,Unnamed: 11
0,FG0003,FG0003,LB0648,Aroma butter Scotch Label 500 gm (Roll Form),2.00000,Nos,0.5,1800.0,900.0,1800.000,NaN,NaN
1,FG0003,FG0003,PK0014,BOPP Tape Roll (Printed) 60 mm X 65 Mtr,0.00080,NO,0.5,1800.0,900.0,0.720,NaN,NaN
2,FG0003,FG0003,PK0016,Caps For HDPE Bottle 500 ML (Aroma),2.00000,NO,0.5,1800.0,900.0,1800.000,NaN,NaN
3,FG0003,FG0003,PK0061,HDPE Round Bottle 500 ML (Aroma),2.00000,NO,0.5,1800.0,900.0,1800.000,NaN,NaN
4,FG0003,FG0003,PK0077,Strapping Roll,0.00330,KG,0.5,1800.0,900.0,2.970,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1392,RFG110,RF2232,RM2202,NaN,0.41500,KG,NaN,1700.0,1700.0,705.500,NaN,NaN
1393,RFG110,RFG110,RM2029,NaN,0.00400,KG,NaN,1700.0,1700.0,6.800,NaN,NaN
1394,RFG110,RFG110,RM2033,NaN,0.00150,KG,NaN,1700.0,1700.0,2.550,NaN,NaN
1395,RFG110,RFG110,RM2174,NaN,0.41088,KG,NaN,1700.0,1700.0,698.496,NaN,NaN
1396,RFG110,RFG110,RM2416,NaN,0.00300,KG,NaN,1700.0,1700.0,5.100,NaN,NaN

In [69]:
from collections import defaultdict
comparison_dict = defaultdict(dict)

for i in range(len(df)):
    comparison_dict[df.iloc[i]['FG_Item']][df.iloc[i]['Child_Item']] = float(df.iloc[i]['Projected qty'])

In [70]:
comparison_dict['FG0003']

{'LB0648': 1800.0,
 'PK0014': 0.72,
 'PK0016': 1800.0,
 'PK0061': 1800.0,
 'PK0077': 2.97,
 'PK0093': 149.4,
 'PK0131': 1800.0,
 'PM064': 840.24,
 'PX166': 23.7789,
 'RM2044': 16.8048,
 'RM2159': 779.6583,
 'RM2184': 16.8048,
 'RM2185': 1.5966,
 'RM2212': 1.5966,
 'RM2158': 5.22,
 'RM2173': 2.34,
 'RM2504': 9.0,
 'RM2505': 43.2}

In [61]:
headers = [
    "Item_Type", 
    "Parent_Code", 
    "Child_Code", 
    "Item_Name", 
    "Component_Code", 
    "BOM_Type", 
    "Quantity"
]


df2 = pd.read_csv('tropolite_verification/Yesterday bom-Table 1.csv', header=None, names=headers)

In [57]:
df2.iloc[0][1]

/var/folders/sz/yhwhpqt538b58w4504fnch580000gn/T/ipykernel_18560/954693248.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df2.iloc[0][1]

'FG0003'

In [62]:
df2

,Item_Type,Parent_Code,Child_Code,Item_Name,Component_Code,BOM_Type,Quantity
0,PM-Indigenous,FG0003,FG0003,Aromas Butter Scotch,PK0014,BOM Item,0.72
1,PM-Indigenous,FG0003,FG0003,Aromas Butter Scotch,PK0016,BOM Item,"1,800.00"
2,PM-Indigenous,FG0003,FG0003,Aromas Butter Scotch,PK0061,BOM Item,"1,800.00"
3,PM-Indigenous,FG0003,FG0003,Aromas Butter Scotch,PK0077,BOM Item,5.94
4,PM-Indigenous,FG0003,FG0003,Aromas Butter Scotch,PK0093,BOM Item,149.4
...,...,...,...,...,...,...,...
1395,RM-Indigenous,RFG110,RFG110,Tropigel Sponge Mix- Chocolate (5 kg),RM2033,Formula Item,2.55
1396,RM-Indigenous,RFG110,RFG110,Tropigel Sponge Mix- Chocolate (5 kg),RM2174,Formula Item,698.5
1397,RM-Indigenous,RFG110,RF2232,Tropigel Sponge Mix- Chocolate (5 kg),RM2202,Formula Item,705.5
1398,RM-Indigenous,RFG110,RFG110,Tropigel Sponge Mix- Chocolate (5 kg),RM2416,Formula Item,5.1
1399,NaN,RFG110,RFG110,Tropigel Sponge Mix- Chocolate (5 kg),NaN,BOM Item,0

In [71]:
comparison_dict_2 = defaultdict(dict)

for i in range(len(df2)):
    comparison_dict_2[df2.iloc[i]['Parent_Code']][df2.iloc[i]['Component_Code']] = df2.iloc[i]['Quantity']

In [73]:
comparison_dict_2['FG0003']

{'PK0014': '0.72',
 'PK0016': '1,800.00',
 'PK0061': '1,800.00',
 'PK0077': '5.94',
 'PK0093': '149.4',
 'PK0131': '1,800.00',
 'PM064': '840.24',
 'PX166': '23.78',
 'RM2044': '16.8',
 'RM2158': '5.22',
 'RM2159': '779.66',
 'RM2173': '2.34',
 'RM2184': '16.8',
 'RM2185': '1.6',
 'RM2212': '1.6',
 'RM2504': '9',
 'RM2505': '43.2'}

In [82]:
df['FG_Item'].unique()

array(['FG0003', 'FG0007', 'FG0020', 'FG0036', 'FG0072', 'FG0083',
       'FG0125', 'FG0126', 'FG0147', 'FG0163', 'FG0165', 'FG0166',
       'FG0167', 'FG0171', 'FG0175', 'FG0261', 'FG0369', 'FG0375',
       'FG0378', 'FG0545', 'FG0546', 'FG0591', 'FG0600', 'FG0611',
       'FG0638', 'FG0666', 'FG0668', 'FG0670', 'FG0694', 'FG0704',
       'FG0705', 'FG0706', 'FG0709', 'FG0732', 'FG0733', 'FG0734',
       'FG0735', 'FG0739', 'FG0741', 'FG0747', 'FG0748', 'FG0750',
       'FG0781', 'FG0782', 'FG0789', 'FG0808', 'FG0834', 'FG0835',
       'FG0840', 'FG0843', 'FG0863', 'FG0877', 'FG1080', 'FG1245',
       'FG1249', 'FG1253', 'FG1254', 'FG1256', 'FG1258', 'FG1259',
       'FG1294', 'FG1317', 'FG1320', 'FG1405', 'FG1429', 'FG1432',
       'FG1433', 'FG1438', 'FG1443', 'FG1444', 'FG1499', 'FG1555',
       'FG1564', 'FG1929', 'FG1930', 'FG1931', 'FG1939', 'FG1952',
       'FG1966', 'FG1970', 'FG1976', 'FG1980', 'FGE005', 'FGE006',
       'FGE050', 'FGE108', 'FGE156', 'RFG011', 'RFG013', 'RFG014',
       'RFG015', 'RFG016', 'RFG017', 'RFG042', 'RFG051', 'RFG061',
       'RFG063', 'RFG076', 'RFG091', 'RFG095', 'RFG098', 'RFG100',
       'RFG105', 'RFG110'], dtype=object)

In [87]:
df2['Parent_Code'].unique()

array(['FG0003', 'FG0007', 'FG0020', 'FG0036', 'FG0071', 'FG0072',
       'FG0083', 'FG0125', 'FG0126', 'FG0147', 'FG0163', 'FG0165',
       'FG0166', 'FG0167', 'FG0171', 'FG0175', 'FG0261', 'FG0369',
       'FG0375', 'FG0378', 'FG0545', 'FG0546', 'FG0591', 'FG0600',
       'FG0611', 'FG0638', 'FG0666', 'FG0668', 'FG0670', 'FG0694',
       'FG0704', 'FG0705', 'FG0706', 'FG0709', 'FG0732', 'FG0733',
       'FG0734', 'FG0739', 'FG0741', 'FG0747', 'FG0748', 'FG0750',
       'FG0781', 'FG0782', 'FG0789', 'FG0808', 'FG0834', 'FG0835',
       'FG0843', 'FG0863', 'FG1080', 'FG1245', 'FG1249', 'FG1253',
       'FG1254', 'FG1256', 'FG1258', 'FG1259', 'FG1294', 'FG1317',
       'FG1320', 'FG1405', 'FG1429', 'FG1432', 'FG1433', 'FG1438',
       'FG1443', 'FG1444', 'FG1499', 'FG1555', 'FG1564', 'FG1929',
       'FG1930', 'FG1931', 'FG1939', 'FG1952', 'FG1970', 'FG1976',
       'FG1980', 'FGE005', 'FGE006', 'FGE050', 'FGE108', 'FGE156',
       'Finish Good', 'RFG011', 'RFG013', 'RFG014', 'RFG015', 'RFG016',
       'RFG017', 'RFG042', 'RFG051', 'RFG061', 'RFG063', 'RFG076',
       'RFG091', 'RFG095', 'RFG098', 'RFG100', 'RFG105', 'RFG110'],
      dtype=object)

In [92]:
not_available = []
for i in range(104):
    if df['FG_Item'].unique()[i] not in df2['Parent_Code'].unique():
        print(df['FG_Item'].unique()[i])
        not_available.append(df['FG_Item'].unique()[i])

FG0735
FG0840
FG0877
FG1966

In [116]:
final_comparison_dict = defaultdict(dict)

for item in comparison_dict:
    if item not in not_available:
        for comparison_item in comparison_dict_2[item]:
            if comparison_item in comparison_dict[item]:
                try:
                  val = float(str(comparison_dict_2[item][comparison_item]).replace(',', ''))
                  final_comparison_dict[item][comparison_item] = abs(val - comparison_dict[item][comparison_item])
                except Exception as e:
                    print("Skipping key {comparison_item} due to conversion error: {e}")

In [127]:
round(final_comparison_dict['FG0003']['PX166'],2)

0.0

In [128]:
final_comparison_dict

defaultdict(dict,
            {'FG0003': {'PK0014': 0.0,
              'PK0016': 0.0,
              'PK0061': 0.0,
              'PK0077': 2.97,
              'PK0093': 0.0,
              'PK0131': 0.0,
              'PM064': 0.0,
              'PX166': 0.001100000000000989,
              'RM2044': 0.004799999999999471,
              'RM2158': 0.0,
              'RM2159': 0.0016999999999143256,
              'RM2173': 0.0,
              'RM2184': 0.004799999999999471,
              'RM2185': 0.0034000000000000696,
              'RM2212': 0.0034000000000000696,
              'RM2504': 0.0,
              'RM2505': 0.0},
             'FG0007': {'LB0681': 1320.0,
              'PK0014': 0.0020000000000000018,
              'PK0016': 0.0,
              'PK0061': 0.0,
              'PK0077': 2.1820000000000004,
              'PK0093': 0.0,
              'PK0131': 0.0,
              'PM064': 0.0,
              'PX166': 0.0005399999999990968,
              'RM2044': 0.00280000000000058,
              'RM2158': 0.0,
              'RM2159': 0.0012600000000020373,
              'RM2184': 0.00280000000000058,
              'RM2185': 0.0030999999999999917,
              'RM2188': 0.0,
              'RM2212': 0.0030999999999999917},
             'FG0020': {'PC005': 0.004589999999999872,
              'PC006': 0.0008200000000000429,
              'PK0014': 0.0030000000000001137,
              'PK0138': 0.0,
              'PK0446': 0.003400000000056025,
              'PK0573': 0.00019999999999997797,
              'PX227A': 0.0024999999999977263,
              'PX227B': 0.002999999999985903,
              'RF2435': 0.0025000000000545697,
              'RF2624': 0.0,
              'RM2034': 0.0030000000000001137,
              'RM2037': 0.0030000000000001137,
              'RM2117': 0.007033999999976004,
              'RM2118': 0.012033999999971456,
              'RM2159': 8249.21986,
              'RM2167': 0.003570000000000073,
              'RM2174': 0.021165999999539054,
              'RM2211': 0.003570000000000073,
              'RM2764': 0.0024999999999977263},
             'FG0036': {'PK0037': 0.0,
              'PK0113': 0.0,
              'PK0123': 0.0,
              'PK0211': 0.0,
              'PK0258': 0.0,
              'PX273A': 0.0,
              'PX273B': 0.0,
              'RF2232': 0.0,
              'RM2152': 0.0,
              'RM2174': 0.0,
              'RM2183': 0.0,
              'RM2202': 0.0,
              'RM2257': 0.0,
              'RM2652': 0.0},
             'FG0072': {'PK0037': 0.0,
              'PK0113': 0.004999999999999893,
              'PK0123': 0.0030000000000001137,
              'PK0211': 0.0,
              'PK0258': 0.0,
              'PX150A': 0.0,
              'PX150B': 0.0,
              'RF2232': 0.0,
              'RM2174': 0.0,
              'RM2177': 0.0,
              'RM2202': 0.0},
             'FG0083': {'PK0037': 0.0,
              'PK0113': 0.0,
              'PK0211': 0.0,
              'PK0258': 0.0,
              'RM2201': 0.0},
             'FG0125': {'PK0037': 0.005000000000000782,
              'PK0113': 0.0025000000000001688,
              'PK0211': 0.0,
              'PK0258': 0.0,
              'RM2174': 0.0,
              'RM2201': 0.0},
             'FG0126': {'LB0696': 0.004455407320399729,
              'PK0064': 0.0018265351121549978,
              'PK0113': 0.0040867324439227,
              'PK0211': 0.004625730342540102,
              'PK0275': 0.002312865171270051,
              'PK0350': 0.003074853931491095,
              'PX186A': 1.3449445310342867e-05,
              'PX186B': 0.001550876411049451,
              'RM2166': 0.0037426965745979146},
             'FG0147': {'LB0696': 0.00403462957527001,
              'PK0064': 0.0023915844450966978,
              'PK0113': 0.0011957922225483975,
              'PK0211': 0.0028910814640901172,
              'PK0275': 0.0014455407320401736,
              'PK0350': 0.0005782162928180123,
              'PX191': 0.002534726091198536,
              'RM2174': 0.0013267556077405374},
             'FG0163': {'PK0038': 0.0005667599391703249,
              'PK0113': 0.003178133744296985,
              'PK0211': 0.00283379969580011,
              'PK0275': 0.0014168998479195949,
              'PX488': 0.004250699543799641,
              'RM2158': 0.004242915500760398,
              'RM2173': 0.002878542249619802,
              'RM2174': 0.0007548324620074709,
              'RM2490': 0.0017813374429698214},
             'FG0165': {'LB0696': 0.0010388872585007647,
              'PK0064': 0.0032524666471019925,
              'PK0113': 0.0033737666764489943,
              'PK0211': 0.0032675560772799095,
              'PK0275': 0.0033662219613599387,
              'PK0350': 0.0026535112154559837,
              'PX488': 9.866588407980714e-05,
              'RM2174': 0.00668462541649717,
              'RM2187': 0.002844573376376003,
              'RM2191': 0.00021683110980679973},
             'FG0166': {'PK0038': 0.003868261349300184,
              'PK0113': 0.0002623504985099778,
              'PK0211': 0.0006586932539960344,
              'PK0275': 0.00032934662679906523,
              'PX488': 0.0009880398800135026,
              'RM2113': 0.0040329346626801765,
              'RM2162': 0.00028065869325399895,
              'RM2174': 0.002932032429953324},
             'FG0167': {'PK0113': 0.0036169591698502757,
              'PK0211': 0.00042884427404032976,
              'PK0275': 0.00021442213702016488,
              'PK0559': 0.0019142311451005867,
              'PX488': 0.0006432664119984111,
              'RM2174': 0.0033678980303193384,
              'RM2211': 0.0036169591698502757,
              'RM2461': 0.001702144221369828},
             'FG0171': {'LB0696': 0.0014354811119012822,
              'PK0064': 0.0002627742266569921,
              'PK0113': 0.00013138711332799646,
              'PK0211': 0.0003406460441794934,
              'PK0275': 0.0001703230220897467,
              'PK0350': 0.001931870791159973,
              'PX196': 0.0028709622238025645,
              'RM2055': 0.0028709622238025645},
             'FG0175': {'LB0696': 0.0021038887258499894,
              'PK0064': 0.002174753335289801,
              'PK0113': 0.0010873766676449004,
              'PK0211': 0.001326755607728991,
              'PK0275': 0.0043366221961360085,
              'PK0350': 0.0017346488784539954,
              'PX198': 0.004459024703349801,
              'RM2208': 0.0028745796067397578},
             'FG0261': {'LB0696': 0.0019307408493993705,
              'PK0064': 0.004783168890193007,
              'PK0113': 0.0023915844450966006,
              'PK0211': 0.0042178370718204405,
              'PK0275': 0.0028910814640901172,
              'PK0350': 0.0011564325856370239,
              'PX335': 0.0019307408493993705,
              'RM2051': 0.0016831109807000644,
              'RM2192': 0.00337628158149883,
              'RM2199': 0.004099051947500598},
             'FG0369': {'PC005': nan,
              'PC006': nan,
              'PK0003': 0.0,
              'PK0014': 0.004500000000007276,
              'PK0442': 0.0010000000002037268,
              'PK0573': 0.0002999999999993008,
              'PX223A': 0.0028500000000803993,
              'PX223B': 0.004500000000007276,
              'RF2431': nan,
              'RF2624': nan,
              'RM2034': 0.004500000000007276,
              'RM2117': 0.14640199999848846,
              'RM2118': 0.07320100000015373,
              'RM2159': 17418.605171000003,
              'RM2167': 0.003090000000000259,
              'RM2174': 0.0027249999984633178,
              'RM2211': 0.003090000000000259},
             'FG0375': {'LB0353': 261.0,
              'PK0064': 0.077,
              'PK0066': 0.003999999999999976,
              'PM101': 26.1,
              'PX238': 2.3499999999999996,
              'RM2158': 0.26,
              'RM2159': 2.61,
              'RM2201': 20.6403,
              'RM2204': 0.2397},
             'FG0378': {'PC005': 0.0034240000000007598,
              'PC006': 0.0068480000000015195,
              'PK0014': 0.0020000000000095497,
              'PK0088': 0.0,
              'PK0443': 0.004000000000814907,
              'PK0573': 0.0031999999999996476,
              'PX513A': 0.061144000000012966,
              'PX513C': 0.06724399999984598,
              'RF2624': 0.0,
              'RF2638': 0.0,
              'RM2034': 0.0020000000000095497,
              'RM2037': 0.06594400000000178,
              'RM2117': 0.060244000000238884,
              'RM2118': 0.060244000000238884,
              'RM2159': 59593.826799999995,
              'RM2167': 0.060744000000000575,
              'RM2174': 0.005135999999765772,
              'RM2177': 0.0,
              'RM2211': 0.060744000000000575,
              'RM2492': 0.0,
              'RM2500': 0.0020000000000095497},
             'FG0545': {'PK0038': 0.0006758903392025672,
              'PK0113': 0.003500864719300001,
              'PK0211': 0.00337945169599152,
              'PK0275': 0.0033102741519996925,
              'PX158A': 0.00010736612200901163,
              'PX158B': 8.647193001820597e-05,
              'RM2019': 0.0026689725848001444,
              'RM2033': 0.00010051883157990993,
              'RM2149': 0.003290675890339198,
              'RM2161': 0.0008866551370759999,
              'RM2174': 0.005921076940012426,
              'RM2215': 0.003793414040467985,
              'RM2557': 0.004003458877200217},
             'FG0546': {'PK0038': 0.0012773677378987713,
              'PK0113': 0.0032447532254300526,
              'PK0211': 0.0036131613099996684,
              'PK0275': 0.00319341934502404,
              'PX156A': 0.004736527406009827,
              'PX156B': 0.001229043897012616,
              'RM2019': 0.0007338061303023835,
              'RM2033': 0.003946851935260121,
              'RM2161': 0.002976596709672402,
              'RM2174': 0.001476119929975539,
              'RM2215': 0.0013377623387279547},
             'FG0591': {'LB0696': 0.0,
              'PK0064': 0.0,
              'PK0113': 0.0050000000000000044,
              'PK0123': 0.00014999999999999736,
              'PK0211': 0.0,
              'PK0258': 0.0,
              'PK0349': 0.0,
              'PX244A': 0.004999999999999893,
              'PX244B': 0.004999999999999893,
              'RF2232': 0.0,
              'RM2174': 0.0,
              'RM2202': 0.0},
             'FG0600': {'PC005': 0.0022500000000000853,
              'PC006': 0.0045000000000001705,
              'PK0014': 0.0025000000000048317,
              'PK0122': 0.0,
              'PK0445': 0.0014999999998508429,
              'PK0573': 0.0045000000000001705,
              'PX225A': 0.002250000000003638,
              'PX225B': 0.0025000000000545697,
              'RF2431': 0.016314999999849533,
              'RF2624': 0.0,
              'RM2034': 0.0025000000000048317,
              'RM2117': 0.032629999999699066,
              'RM2118': 0.016315000000076907,
              'RM2159': 3325.2168650000003,
              'RM2167': 0.003349999999999964,
              'RM2174': 0.0016250000007858034,
              'RM2211': 0.003349999999999964},
             'FG0611': {'PK0038': 0.004101311831000487,
              'PK0113': 0.0003844979841519658,
              'PK0211': 0.0005065591548003567,
              'PK0275': 0.00025327957740017837,
              'PX246': 0.006200806339052178,
              'RM2174': 0.002532795773959151},
             'FG0638': {'LB0612': 0.0,
              'LB0613': 0.0,
              'PK0014': 0.0040000000000000036,
              'PK0066': 0.001999999999995339,
              'PK0077': 0.0007999999999999119,
              'PK0123': 0.0037599999999997635,
              'PK0467': 0.0,
              'PK0468': 0.004799999999988813,
              'PX461': 0.004559999999997899,
              'R&D208': 0.0040000000000000036,
              'RF2583': 0.0,
              'RM2045': 0.0023199999999974352,
              'RM2117': 0.002960000000001628,
              'RM2118': 0.0035199999999946385,
              'RM2138': 0.004399999999999515,
              'RM2159': 7.999999999697138e-05,
              'RM2185': 0.0017599999999999838,
              'RM2189': 0.0,
              'RM2262': 0.0031999999999996476,
              'RM2492': 0.0016800000000216642},
             'FG0666': {'PK0113': 0.005000000000002558,
              'PK0123': 0.002549999999999386,
              'PK0211': 0.0,
              'PK0258': 0.0,
              'PK0585': 0.0,
              'PX018A': 0.0049999999999954525,
              'PX018B': 0.0,
              'RF2232': 0.0,
              'RM2058': 0.0,
              'RM2174': 0.005000000000109139,
              'RM2202': 0.0},
             'FG0668': {'PK0037': 0.0,
              'PK0113': 0.0,
              'PK0123': 0.0029999999999998916,
              'PK0211': 0.0,
              'PK0258': 0.0,
              'PX152A': 0.0,
              'PX152B': 0.0,
              'RF2232': 0.0,
              'RM2174': 0.0,
              'RM2202': 0.0},
             'FG0670': {'PK0037': 0.0049999999999954525,
              'PK0113': 0.0024999999999999467,
              'PK0123': 0.0036000000000000476,
              'PK0211': 0.0,
              'PK0258': 0.0,
              'PX052A': 0.005000000000023874,
              'PX052B': 0.0049999999999954525,
              'RF2232': 0.0025000000000545697,
              'RM2174': 0.0025000000000545697,
              'RM2183': 0.005000000000009663,
              'RM2202': 0.0025000000000545697},
             'FG0694': {'LB0246': 0.0,
              'PK0014': 0.0023999999999999577,
              'PK0044': 0.0020000000000095497,
              'PK0077': 0.0020000000000000018,
              'PK0097': 0.0,
              'PK0270': 0.0,
              'PX460A': 0.003999999999990678,
              'PX460B': 0.0040000000000048885,
              'RM2019': 0.0026000000000000467,
              'RM2044': 0.0040800000000000836,
              'RM2054': 0.0006399999999997519,
              'RM2077': 0.0045599999999998975,
              'RM2117': 0.0,
              'RM2159': 0.0026400000000137425,
              'RM2174': 0.0,
              'RM2185': 0.0045599999999998975,
              'RM2199': 0.003720000000001278,
              'RM2241': 0.0033600000000000296,
              'RM2784': 0.0040000000000000036},
             'FG0704': {'LB0696': 0.002969628107898359,
              'PK0064': 0.0019643644627049817,
              'PK0113': 0.0009821822313529904,
              'PK0123': 0.0016917861867762,
              'PK0211': 0.0009502809945294288,
              'PK0275': 0.00047514049725982943,
              'PK0350': 0.003809943801089899,
              'PX248': 0.00043597703080067163,
              'RF2581': 0.003928728925409963,
              'RM2055': 0.0033853760429991553,
              'RM2174': 0.0019858882832011204,
              'RM2212': 0.003928728925409963},
             'FG0705': {'LB0255': 0.0,
              'PK0014': 0.0019999999999997797,
              'PK0044': 0.0,
              'PK0077': 0.0024999999999995026,
              'PK0097': 0.0,
              'PK0270': 0.0,
              'PX088': 0.0035999999999987153,
              'PX118': 0.002899999999996794,
              'PX340': 0.002600000000001046,
              'RM2079': 0.0014999999999999458,
              'RM2159': 0.000349999999798456,
              'RM2189': 0.001150000000052387,
              'RM2212': 0.0031999999999996476,
              'RM2492': 0.0028999999999541615},
             'FG0706': {'LB0269': 0.0,
              'PK0014': 0.0,
              'PK0044': 0.0,
              'PK0077': 0.0025000000000000577,
              'PK0097': 0.0,
              'PK0270': 0.0,
              'PX088': 0.0040000000000000036,
              'PX118': 0.0015000000000000568,
              'PX340': 0.001000000000000334,
              'RM2159': 0.004099999999993997,
              'RM2188': 0.0,
              'RM2189': 0.001599999999996271,
              'RM2212': 0.0020000000000000018,
              'RM2492': 0.004750000000001364,
              'RM2517': 0.004250000000000004},
             'FG0709': {'LB0256': 0.0,
              'PK0014': 0.0040000000000000036,
              'PK0044': 0.0,
              'PK0077': 0.0025000000000000022,
              'PK0097': 0.0,
              'PK0270': 0.0,
              'PX088': 0.0008000000000001339,
              'PX118': 0.0036999999999998145,
              'PX340': 0.0,
              'RM2159': 0.002200000000001978,
              'RM2173': 0.000975,
              'RM2189': 0.0045000000000001705,
              'RM2212': 0.00040000000000006697,
              'RM2490': 0.0,
              'RM2492': 0.000775000000004411,
              'RM2517': 0.0050000000000000044},
             'FG0732': {'LB0190': 0.0,
              'PK0014': 0.0,
              'PK0044': 0.0,
              'PK0077': 0.0,
              'PK0097': 0.0,
              'PK0270': 0.0,
              'PX088': 0.0032000000000005357,
              'PX118': 0.0,
              'RM2045': 0.0,
              'RM2079': 0.002999999999999989,
              'RM2138': 0.0,
              'RM2159': 0.00380000000001246,
              'RM2180': 0.0,
              'RM2189': 0.0,
              'RM2212': 0.0,
              'RM2230': 0.0,
              'RM2262': 0.0,
              'RM2492': 0.0},
             'FG0733': {'LB0040': 0.0,
              'PK0014': 0.0020000000000000018,
              'PK0044': 0.0,
              'PK0077': 0.0024999999999999467,
              'PK0097': 0.0,
              'PK0270': 0.0,
              'PX118': 0.0024999999999995026,
              'PX173': 0.0034999999999989484,
              'PX360': 0.0,
              'RM2033': 0.0024999999999999467,
              'RM2039': 0.0019999999999988916,
              'RM2045': 0.0024999999999977263,
              'RM2058': 0.0049999999999954525,
              'RM2059': 0.0004999999999997229,
              'RM2159': 0.0,
              'RM2189': 0.0040000000000048885,
              'RM2212': 0.004999999999999893,
              'RM2492': 0.004500000000007276},
             'FG0734': {'LB0241': 0.0,
              'PK0014': 0.0020000000000000018,
              'PK0077': 0.0024999999999999467,
              'PK0097': 0.0,
              'PK0104': 0.0,
              'PK0270': 0.0,
              'PX088': 0.004399999999999515,
              'PX118': 0.0,
              'RM2079': 0.002005,
              'RM2159': 0.000994999999988977,
              'RM2189': 0.0,
              'RM2212': 0.0014000000000000679,
              'RM2492': 0.0},
             'FG0739': {'LB0170': 0.0,
              'PK0014': 0.0040000000000000036,
              'PK0044': 0.0,
              'PK0077': 0.0025000000000000022,
              'PK0097': 0.0,
              'PK0270': 0.0,
              'PX337': 0.0,
              'PX338': 0.0,
              'RM2128': 0.0,
              'RM2134': 0.0024999999999999988,
              'RM2159': 0.0030000000000001137,
              'RM2178': 0.0050000000000000044,
              'RM2185': 0.0040000000000000036,
              'RM2189': 0.0008999999999996788,
              'RM2212': 0.0050000000000000044,
              'RM2230': 0.0020000000000000018,
              'RM2260': 0.001999999999999988,
              'RM2262': 0.0009,
              'RM2492': 0.001000000000000334,
              'RM2517': 0.0017000000000000001},
             'FG0741': {'LB0160': 0.0,
              'PK0014': 0.001999999999999988,
              'PK0044': 0.0,
              'PK0077': 0.0050000000000000044,
              'PK0097': 0.0,
              'PK0270': 0.0,
              'PX337': 0.0,
              'PX338': 0.0,
              'RM2134': 0.0050000000000000044,
              'RM2159': 0.0020000000000024443,
              'RM2173': 0.0019000000000000006,
              'RM2178': 0.0,
              'RM2185': 0.001999999999999988,
              'RM2189': 0.004300000000000637,
              'RM2194': 0.0,
              'RM2212': 0.0,

In [147]:
missed_product_dict = defaultdict(dict)

for item in final_comparison_dict:
    for codes in final_comparison_dict[item]:
        if round(final_comparison_dict[item][codes],2) > 1:
            missed_product_dict[item][codes] = final_comparison_dict[item][codes]

In [152]:
for i in missed_product_dict:
    print(i)

FG0003
FG0007
FG0020
FG0369
FG0375
FG0378
FG0600
FG0781
FG0782
FG1317
FG1405
FG1433
FG1564
FG1929
FG1931
FG1970
FG1976
FG1980
FGE005
FGE006
FGE050
FGE156
RFG061

In [153]:
missed_product_dict['FG0020']

{'RM2159': 8249.21986}

In [150]:


# 1. Flatten the nested missed_product_dict
series = pd.Series({(prod, item): val 
                    for prod, item_dict in missed_product_dict.items() 
                    for item, val in item_dict.items()})

# 2. Convert to DataFrame and name columns
df_missed = series.reset_index()
df_missed.columns = ['Product', 'Missed_Item', 'Value']

# 3. Save to Excel
df_missed.to_excel('missed_products_list.xlsx', index=False)